{
 "title": "Graph styles",
 "tags": [
  "annotations",
  "demo",
  "presentation"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Simple graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(apps.backend.*.counters.requests.count,1),2)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "#### Simple graph\n- Click on the title and select edit to open edit mode\n- The display styles tab allows you change line width, fill, stacking, and more\n- You can change a series color by clicking the colored line in the legend "
   }
  },
  {
   "title": "Points",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(apps.fakesite.*.counters.requests.count, 2)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "#### Points\n- Points enabled\n- Mixing in line fill but with line width set to zero\n- Gradient area fill"
   }
  },
  {
   "title": "Stacked lines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Requests / s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(apps.fakesite.*.counters.requests.count,1),2)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "options": {
    "content": "#### Staircase & Y-Axis format\n- In display styles tab you can switch to staircase line \n- In Axes & Grid tab you can change to different Y units & formats.\n"
   }
  },
  {
   "title": "Staircase line",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.upper_90,4)"
    },
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.upper_90,4)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "options": {
    "content": "#### Second Y-Axis\n- Click on the series legend color line to open the color selector\n- In the series color selector popup you can also move the series to the Right-Y axis\n- Multiple Y-Axis are great for showing to related series that have different magnitudes "
   }
  },
  {
   "title": "Memory / CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(scale(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count,1),1000000),'memory')"
    },
    {
     "target": "alias(scaleToSeconds(apps.fakesite.web_server_02.counters.requests.count,1),'cpu')"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "options": {
    "content": "#### Mix styles\n\n* You can now override and set any display style for a specific series\n* You find these options under Display styles tab when in graph edit mode\n* These overrides can be set using the series name or a regex pattern"
   }
  },
  {
   "title": "server requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(statsd.fakesite.timers.ads_timer.upper_90, 'cpu')"
    },
    {
     "target": "aliasByNode(movingAverage(apps.fakesite.*.counters.requests.count, 2), 2)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "options": {
    "content": "#### Null point mode\n- This option under Display styles tab controls how null values are handled\n- The graph to left shows how the default \"null\" looks. \n- __null__   null values are left null and this leaves empty spaces in the graph\n- __null as zero__   null values are drawn as zero values\n- __connected__   null values are ignored and the line jumps directly to the next value."
   }
  },
  {
   "title": "Null point mode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(apps.fakesite.web_server_01.counters.request_status.code_404.count,4)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "options": {
    "content": "#### Thresholds\n- You can define thresholds in the Grid & Axes tab in edit mode \n- You can define one or two thresholds, color is also changeable. \n- You can have lower bound thresholds as well. "
   }
  },
  {
   "title": "Thresholds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(apps.fakesite.web_server_01.counters.requests.count,4)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
   "options": {
    "content": "#### Bars\n- In display styles tab you can switch from line to bars\n- The width of the bar is relative to the pixel width between two values\n"
   }
  },
  {
   "title": "Bars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '1min', 'sum', false), 4)"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "options": {
    "content": "#### Series Mode - Bars\n\n- On the Axes tab, you can switch the mode from Time to Series mode to group the value by series instead of time interval.\n"
   }
  },
  {
   "title": "X-axis Series Mode - Bars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.*,4)"
    }
   ]
  }
 ]
}