{
 "title": "SAS CAS Overview with Logs",
 "description": "SAS Viya CAS dashboard",
 "tags": [
  "sas-viya",
  "welcome-viya"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cas_build_info,namespace)"
    }
   },
   {
    "name": "casServer",
    "label": "CAS Server",
    "query": {
     "query": "label_values(cas_build_info{namespace=~\"$namespace\"},cas_server)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CAS Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CAS Server Info",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(cas_build_info{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\"} + on (cas_server,namespace) group_left(name,release,system,version) cas_os_info{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\"}) + on (cas_server, namespace) group_left(state) cas_grid_state{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\"}"
    }
   ]
  },
  {
   "title": "Current Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cas_grid_sessions_current{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cas_grid_uptime_seconds_total{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\"}"
    }
   ]
  },
  {
   "title": "CPU by Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cas_node_cpu_time_seconds{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\",type=~\"user|system\"}[1m])) by (cas_node)",
     "legendFormat": "{{cas_node}}"
    }
   ]
  },
  {
   "title": "Memory by Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Physical" }
   ],
   "targets": [
    {
     "expr": "(cas_node_mem_size_bytes{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\",type=\"physical\"}-cas_node_mem_free_bytes{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\",type=\"physical\"})",
     "legendFormat": "{{cas_node}}"
    }
   ]
  },
  {
   "title": "Total CPU by Node Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum by (cas_node_type) (rate(cas_node_cpu_time_seconds{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\",type=~\"user|system\"}[1m]))",
     "legendFormat": "{{cas_node_type}}s"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cas_node_open_files{namespace=~\"$namespace\",cas_server=~\"$casServer\",service=~\".+-client\"}",
     "legendFormat": "{{cas_node}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "logsource.keyword:\"$casServer\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}