{
 "title": "SAS Go Service Details with Logs",
 "description": "Dashboard for Go-based services",
 "tags": [
  "sas-viya",
  "welcome-viya"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(sas_build_info{sas_service_base=\"golang\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(go_info{sas_service_base=\"golang\",namespace=~\"$namespace\"}, service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(go_info{job=\"$application\",namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sas_build_info{job=~\"$application\", pod=~\"$instance\",version=~\".+\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{job=~\"$application\", pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"$instance\",job=~\"$application\"}"
    }
   ]
  },
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$application\", pod=~\"$instance\"}[1m])",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"$instance\",job=~\"$application\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=~\"$application\", pod=~\"$instance\"}",
     "legendFormat": "live"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(log_events_total{job=~\"$application\", pod=~\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$application\", pod=~\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{job=~\"$application\", pod=~\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Database Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Connection Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sas_db_pool_connections{service=~\"$application\",pod=~\"$instance\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sas_db_connections_max{service=~\"$application\",pod=~\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Closed Connections by Reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sas_db_closed_total{job=~\"$application\", pod=~\"$instance\"}[1m])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 24, "w": 18, "x": 0, "y": 28 },
     "targets": [
      {
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "settings": { "limit": "500" },
         "type": "logs"
        }
       ],
       "query": "logsource:\"$application\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}