extraEnvs:
# SERVER_BASEPATH needed for path-based ingress
- name: SERVER_BASEPATH
  value: /dashboards
# OSD_ENABLE_TLS, Username & password need to be set here since helm *replaces* array values
- name: OSD_ENABLE_TLS
  valueFrom:
    secretKeyRef:
      name: v4m-osd-tls-enabled
      key: enable_tls
- name: OPENSEARCH_USERNAME
  valueFrom:
    secretKeyRef:
      name: internal-user-kibanaserver
      key: username
- name: OPENSEARCH_PASSWORD
  valueFrom:
    secretKeyRef:
      name: internal-user-kibanaserver
      key: password
service:
  type: ClusterIP
  nodePort: null

