apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sas-java-pods
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  selector:
    matchExpressions:
    - key: sas.com/deployment
      operator: Exists
  podMetricsEndpoints:
  - port: http-internal
    path: /internal/metrics
    tlsConfig:
      insecureSkipVerify: true
    relabelings:
    # Enable this when a critical mass of Go services have been rebuilt to provide the
    # correct value for the sas.com/kustomize-base annotation
    - sourceLabels: [__meta_kubernetes_pod_annotation_sas_com_kustomize_base]
      regex: spring
      action: keep
    - sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_port]
      regex: "false"
      targetLabel: __port
      replacement: "10445"
    - sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_port,__meta_kubernetes_pod_annotation_prometheus_io_port]
      regex: true;(.+)
      targetLabel: __port
      replacement: $1
    - sourceLabels: [__meta_kubernetes_pod_ip, __port]
      regex: (.+);(.+)
      targetLabel: __address__
      replacement: $1:$2
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: job
    - sourceLabels: [__meta_kubernetes_pod_label_sas_com_deployment]
      targetLabel: sas_deployment    
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_annotation_sas_com_kustomize_base]
      targetLabel: sas_service_base
    - sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scheme,__meta_kubernetes_pod_annotation_prometheus_io_scheme]
      action: replace
      regex: true;(.+)
      targetLabel: __scheme__
      replacement: $1
    metricRelabelings:
    # Rename logback_events_total to have consistency with the
    # Go services metric log_events_total
    # Renaming a metric must be done in metricRelabelings 
    - sourceLabels: [__name__]
      regex: logback_events_total
      targetLabel: __name__
      replacement: log_events_total
