apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sas-go-pods
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  selector:
    matchExpressions:
    - key: sas.com/deployment
      operator: Exists
      values: []
  podMetricsEndpoints:
  - port: http
    path: /internal/metrics
    tlsConfig:
      insecureSkipVerify: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_port, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: true;(.+)
      replacement: $1
      targetLabel: __port
    - sourceLabels: [__meta_kubernetes_pod_ip, __port]
      action: replace
      regex: (.+);(.+)
      replacement: $1:$2
      targetLabel: __address__
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      regex: "sas-arke|sas-launcher|sas-redis-operator|sas-opendistro-exporter"
      action: drop
    - sourceLabels: [__meta_kubernetes_pod_annotation_sas_com_kustomize_base]
      regex: "golang"
      action: keep
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: sas_service_base
      replacement: golang
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: service
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: job
    - sourceLabels: [__meta_kubernetes_pod_label_sas_com_deployment]
      targetLabel: sas_deployment
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
      action: replace
      regex: (https?)
      targetLabel: __scheme__
