apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sas-opendistro
spec:
  endpoints:
  - metricRelabelings:
    - action: replace
      sourceLabels:
      - node
      targetLabel: es_node
    path: /metrics
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-opendistro-exporter