# Refer to https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/stable/ARTIFACT_INVENTORY.md
# to identify the current Helm chart version in use by this project.  The links below point to
# the 'main' branch as a general reference and the contents will likely differ to some degree.

# Chart: https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit
# Default values: https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml


# NOTE: Customizations intended to alter the contents of the Fluent Bit Configuration Files
#       should be made by altering contents of the fluent-bit_config.configmap_open.yaml files.
#       Use this file to customize other Helm chart settings.


#image:
#  tag: 4.0.9

# ***** extraVolumeMounts/extraVolumes - START *****
#
# Resolving symbolic links/Relocated Docker Root Dir
#
# Uncomment the entire following section and edit
# the extraVolumeMounts and extraVolumes stanzas to
# ensure any symbolic links you have defined in your
# environment affecting the location of the container
# logs can be resolved.  This may include changes you
# made to relocate the Docker Root Directory.
#
# For example, in the sample below, the Docker
# Root Directory was mapped to: /data01/var/lib/docker
#
# If any symbolic links affecting the /var/log/containers
# directory cannot be resolved, Fluent Bit
# will run without ERRORs but NO log messages
# will be collected.


#extraVolumeMounts:
#- mountPath: /data01/var/lib/docker/containers
#  name: path2dockercontainers
#  readOnly: true
#extraVolumes:
#- hostPath:
#    path: /data01/var/lib/docker/containers
#    type: ""
#  name: path2dockercontainers

# ***** extraVolumeMounts/extraVolumes - END *****
