# Helm Chart:     https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
# Default values: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/values.yaml

# image:
#   repository: justwatch/elasticsearch_exporter
#   tag: 1.1.0

# es:
#   uri: https://metricgetter:metricgetterpw@v4m-es-client-service.logging:9200
