## Sample: contour/host-based-ingress Version: 0.2.2

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-grafana
spec:
  virtualhost:
    fqdn: grafana.host.cluster.example.com
    tls:
      secretName: v4m-ingress-tls-secret
  routes:
    - conditions:
      - prefix: /
      services:
        - name: v4m-grafana
          port: 3000
          protocol: tls

