sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
  datasources:
    enabled: true
    label: grafana_datasource
persistence:
  type: pvc
  enabled: true
  # Provide custom storageClassName here if needed
  # storageClassName: my-storage-class-here
  finalizers:
    - kubernetes.io/pvc-protection
  accessModes:
    - ReadWriteOnce
  size: 5Gi
# dashboards:
#   default_home_dashboard_path: /tmp/dashboards/viya-welcome-dashboard.json
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    # OpenShift Thanos querier allows access to both cluster
    # and user workload monitoring
    - access: proxy
      editable: false
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        # Replace BEARER_TOKEN below with a token for grafana-serviceaccount
        httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
initChownData:
  enabled: false
# Set to null to disable securityContext for OpenShift
securityContext: null
serviceAccount:
  # Service account created prior to helm install since the token is needed
  # above in the datasource configuration
  create: false
  name: grafana-serviceaccount
testFramework:
  enabled: false
"grafana.ini":
  analytics:
    check_for_updates: false
  log:
    mode: console
  "log.console":
      format: json
