# This is a Prometheus resource that deploys a tenant-specific instance

apiVersion: v1
kind: ServiceAccount
metadata:
  name: v4m-prometheus-__TENANT__
  labels:
    v4m.sas.com/tenant: __TENANT__
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-role-__TENANT__
  labels:
    v4m.sas.com/tenant: __TENANT__
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","services","endpoints","ingresses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding-__TENANT__
  labels:
    v4m.sas.com/tenant: __TENANT__
subjects:
- kind: ServiceAccount
  name: v4m-prometheus-__TENANT__
  apiGroup: ""
roleRef:
  kind: Role
  name: prometheus-role-__TENANT__
  apiGroup: ""
