apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway-__TENANT__
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
    v4m.sas.com/tenant: __TENANT__
spec:
  selector:
    matchLabels:
      app: prometheus-pushgateway
  endpoints:
  - port: http
    relabelings:
    - sourceLabels: [__name__]
      regex: "sas_.+"
      action: keep
    - sourceLabels: [__meta_kubernetes_pod_annotation_sas_com_tls_enabled_ports]
      action: replace
      regex: all|.*http.*
      targetLabel: __scheme__
      replacement: https
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      regex: (https?)
      targetLabel: __scheme__
    - sourceLabels: [app]
      targetLabel: sas_tenant
      replacement: __TENANT__
    tlsConfig:
      insecureSkipVerify: true
