services:
  grafana:
    environment:
      - GF_INSTALL_PLUGINS=grafana-llm-app
      - GF_DEFAULT_APP_MODE=development
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
