{
 "title": "Contour Ingress Metrics",
 "description": "This Grafana dashboard comprehensively monitors the Project Contour Ingress Controller at the service and namespace level (Projectcontour) \n\nhttps://grafana.com/grafana/dashboards/21396-contour-ingress-metrics/",
 "tags": [
  "projectcontour",
  "ingress"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "contour_namespace",
    "label": "Contour Namespace",
    "query": {
     "query": "label_values(contour_build_info,namespace)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{namespace=\"$contour_namespace\"},envoy_cluster_name)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=~\"${namespace}_[a-z0-9\\\\-]+_\\\\d+\"},envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Connections (period)",
   "type": "stat",
   "description": "This is the total number of connections made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "% Success (period)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the entire period in the top-right hand corner.\n\nNOTE: Ignoring 404s in this metric, since a 404 is a normal response for errant/invalid request. ",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\", envoy_response_code_class!~\"4|5\" }[${__range_s}s]\n      )\n   )   \n/ \n(\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_xx{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[${__range_s}s]\n        )\n     ) - \n  (\n  sum(\n    rate(\n      envoy_cluster_upstream_rq{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\", envoy_response_code=~\"404\"}[${__range_s}s]\n        )\n     ) \n  or vector(0)\n  )\n)"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (5m)",
   "type": "stat",
   "description": "This is the number of successful requests in the last five minutes.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{namespace=~\"${contour_namespace}\", envoy_response_code_class=~\"1|2\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx (5m)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{namespace=~\"${contour_namespace}\", envoy_response_code_class=\"5\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[5m])) or vector(0)"
    }
   ]
  },
  {
   "title": "Reqs (5m)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last five minute window",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_total{namespace=~\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[5m]))"
    }
   ]
  },
  {
   "title": "Conns (5m)",
   "type": "stat",
   "description": "This is the number of new connections made to the ingress in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_total{namespace=~\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[5m]))"
    }
   ]
  },
  {
   "title": "% Success (5m)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the last five minutes.\n\nNOTE: Ignoring 404s,  in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\", envoy_response_code_class!~\"4|5\" }[5m]\n      )\n   )   \n/ \n(\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_xx{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[5m]\n        )\n     ) - \n  (\n  sum(\n    rate(\n      envoy_cluster_upstream_rq{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\", envoy_response_code=~\"404\"}[5m]\n        )\n     ) \n  or vector(0)\n  )\n)"
    }
   ]
  },
  {
   "title": "HTTP 3xx (5m)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{namespace=~\"${contour_namespace}\", envoy_response_code_class=\"3\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[5m])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 4xx (5m)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{namespace=~\"${contour_namespace}\", envoy_response_code_class=\"4\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[5m])) or vector(0)"
    }
   ]
  },
  {
   "title": "Upstream Replicas Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream members",
     "type": "stat",
     "description": "The number of healthy replicas of the upstream service members",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "repeat": "service",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(sum(envoy_cluster_membership_healthy{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}) by (envoy_cluster_name)/count(envoy_cluster_membership_healthy{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}) by (envoy_cluster_name), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")",
       "legendFormat": "{{ingress}}"
      }
     ]
    }
   ]
  },
  { "title": "Request Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Ingress Success Requests (non 4|5xx Responses)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(envoy_cluster_upstream_rq{namespace=\"${contour_namespace}\", envoy_response_code=~\"[^45].*\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (envoy_response_code, ingress)",
     "legendFormat": "{{ingress}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Ingress Failed Requests (4|5xx Responses)",
   "type": "timeseries",
   "description": "NOTE: Showing 404s in this metric",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(envoy_cluster_upstream_rq{namespace=\"${contour_namespace}\", envoy_response_code=~\"[45].*\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (envoy_response_code, ingress)",
     "legendFormat": "{{ingress}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx Responses)",
   "type": "timeseries",
   "description": "NOTE: Not including 404s in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\", envoy_response_code_class!~\"4|5\"}[5m]\n      )\n   ) by (envoy_cluster_name) \n/ \n(\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_xx{namespace=\"${contour_namespace}\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\", envoy_response_code!~\"404\"}[5m]\n        )\n     ) by (envoy_cluster_name)\n), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\" )) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Service Total",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(label_replace(rate(envoy_cluster_upstream_cx_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)"
    },
    {
     "expr": "sum(label_replace(rate(envoy_cluster_upstream_rq_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(label_replace(rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (le, ingress_namespace, ingress))"
    },
    {
     "expr": "histogram_quantile(0.90, sum(label_replace(rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (le, ingress))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(label_replace(rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (le, ingress))"
    },
    {
     "expr": "sum(label_replace(irate(envoy_cluster_upstream_cx_rx_bytes_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)"
    },
    {
     "expr": "sum(label_replace(irate(envoy_cluster_upstream_cx_tx_bytes_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(label_replace(irate(envoy_cluster_upstream_cx_rx_bytes_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ ingress }} - In"
      },
      {
       "expr": "-sum(label_replace(irate(envoy_cluster_upstream_cx_tx_bytes_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ ingress }} - Out"
      },
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]))",
       "legendFormat": "Total - In"
      },
      {
       "expr": "-sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]))",
       "legendFormat": "Total - Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total active requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(envoy_cluster_upstream_rq_active{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}, \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "Ingress Request Volume",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(label_replace(rate(envoy_cluster_upstream_rq_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "New Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(increase(envoy_cluster_upstream_rq_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[2m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total active connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(envoy_cluster_upstream_cx_active{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}, \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "Ingress Connection Volume",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(label_replace(rate(envoy_cluster_upstream_cx_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[1m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "New Connections ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(increase(envoy_cluster_upstream_cx_total{namespace=\"${contour_namespace}\", envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\"}[2m]), \"ingress\", \"$1/$2\", \"envoy_cluster_name\", \"^([a-z0-9\\\\-]+)_([a-z0-9\\\\-]+)_\\\\d+$\")) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    }
   ]
  }
 ]
}