kibana:
  extraEnvs:
  # Needed for path-based ingress
  - name: SERVER_BASEPATH
    value: /kibana
  # Username & password need to be set here since helm *replaces* array values
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: username
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: password
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    # ingressClass is not currently supported by the Open Distro helm chart
    # ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite (?i)/kibana/(.*) /$1 break;
        rewrite (?i)/kibana$ / break;
      nginx.ingress.kubernetes.io/rewrite-target: /kibana
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    path: /kibana
    pathType: Prefix
    hosts:
    - host.cluster.example.com
    tls:
    - secretName: kibana-ingress-tls-secret
      hosts:
      - host.cluster.example.com

# Elasticsearch ingress is optional
# Uncomment this section only if external API access is required
# elasticsearch:
#   client:
#     ingress:
#       # ingressClass is not currently supported by the Open Distro helm chart
#       # ingressClassName: nginx
#       annotations:
#         kubernetes.io/ingress.class: nginx
#         nginx.ingress.kubernetes.io/configuration-snippet: |
#           rewrite (?i)/elasticsearch/(.*) /$1 break;
#           rewrite (?i)/elasticsearch$ / break;
#         nginx.ingress.kubernetes.io/rewrite-target: /elasticsearch
#         nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#       enabled: true
#       path: /elasticsearch
#       pathType: Prefix
#       hosts:
#       - host.cluster.example.com
#       tls:
#       - secretName: elasticsearch-ingress-tls-secret
#         hosts:
#         - host.cluster.example.com
