## Included to update the image for Ghostunnel
grafana:
  extraContainers: |
    # Add square/ghosttunnel TLS proxy
    - name: tls-proxy
      args:
      - server
      - --listen=:443
      - --target=127.0.0.1:3000
      - --key=/cert/tls.key
      - --cert=/cert/tls.crt
      - --disable-authentication
      image: __AIRGAP_REGISTRY__/ghostunnel/ghostunnel:v1.7.1
      imagePullPolicy: IfNotPresent
      ports:
      - name: https
        containerPort: 443 
        protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
        readOnlyRootFilesystem: true
        runAsNonRoot: false
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /cert
        name: tls-proxy-secret
        readOnly: true
