{
 "title": "Fluent Bit - Log Message Collection",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(fluentbit_output_proc_bytes_total, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{daemonset=~\"fb-fluent-bit|v4m-fb\"}"
    }
   ]
  },
  {
   "title": "Message Rate (In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "- sum(rate(fluentbit_input_records_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[5m]))",
     "legendFormat": "In "
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{daemonset=~\"fb-fluent-bit|v4m-fb\"}"
    }
   ]
  },
  {
   "title": "Retries and Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(fluentbit_output_retries_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[2m]))",
     "legendFormat": "Retries"
    },
    {
     "expr": "sum (rate(fluentbit_output_retries_failed_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[2m]))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Throughput (Bytes In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "- sum (rate(fluentbit_input_bytes_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[2m]))",
     "legendFormat": "Input Bytes"
    },
    {
     "expr": "sum (rate(fluentbit_output_proc_bytes_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[2m]))",
     "legendFormat": "Output Bytes"
    }
   ]
  },
  {
   "title": "By Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message Rate (In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "- sum(rate(fluentbit_input_records_total{pod!~\"v4m-fb-events.*\", node=~\"$node\"}[5m])) by (node)",
     "legendFormat": "In - {{ node }}"
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod!~\"v4m-fb-events.*\", node=~\"$node\"}[5m])) by (node)",
     "legendFormat": "Out - {{ node }}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod!~\"v4m-fb-events.*\", container=\"fluent-bit\",node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Throughput (Bytes In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "- sum (rate(fluentbit_input_bytes_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Input Bytes - {{ node }}"
    },
    {
     "expr": "sum (rate(fluentbit_output_proc_bytes_total{pod!~\"v4m-fb-events.*\", node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Output Bytes - {{ node }}"
    }
   ]
  },
  {
   "title": "Retries and Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(fluentbit_output_retries_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Retries - {{ node }}"
    },
    {
     "expr": "sum (rate(fluentbit_output_retries_failed_total{pod!~\"v4m-fb-events.*\",node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Failures - {{ node }}"
    }
   ]
  }
 ]
}