grafana:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    ingressClassName: nginx
    tls:
    - hosts:
      - grafana.monitoring.host.cluster.example.com
      secretName: grafana-ingress-tls-secret
    hosts:
    - grafana.monitoring.host.cluster.example.com
    path: /
  "grafana.ini":
    server:
      domain: monitoring.host.cluster.example.com
      root_url: https://grafana.monitoring.host.cluster.example.com
      serve_from_sub_path: false

# Uncomment the following sections to expose Prometheus and/or
# Alertmanager via Ingress. Note that Prometheus and Alertmanager
# do not have any authentication configured by default, and exposing
# an unauthenticated applicaton without other restrictions in place
# is insecure.

# prometheus:
#   # Disable default configuration of NodePort
#   service:
#     type: ClusterIP
#     nodePort: null
#   # Define host-based ingress
#   ingress:
#     annotations:
#       nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#     enabled: true
#     ingressClassName: nginx
#     tls:
#     - hosts:
#       - prometheus.monitoring.host.cluster.example.com
#       secretName: prometheus-ingress-tls-secret
#     hosts:
#     - prometheus.monitoring.host.cluster.example.com
#   prometheusSpec:
#     # routePrefix: /prometheus
#     externalUrl: https://prometheus.monitoring.host.cluster.example.com

# alertmanager:
#   # Disable default configuration of NodePort
#   service:
#     type: ClusterIP
#     nodePort: null
#   # Define host-based ingress
#   ingress:
#     annotations:
#       nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#     enabled: true
#     ingressClassName: nginx
#     tls:
#     - hosts:
#       - alertmanager.monitoring.host.cluster.example.com
#       secretName: alertmanager-ingress-tls-secret
#     hosts:
#     - alertmanager.monitoring.host.cluster.example.com
#   alertmanagerSpec:
#     # routePrefix: /alertmanager
#     externalUrl: https://alertmanager.monitoring.host.cluster.example.com
