{
 "title": "SAS CAS Overview",
 "description": "SAS Viya CAS dashboard prototype",
 "tags": [ "sas-viya" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(cas_build_info,namespace)"
   },
   {
    "name": "casServer",
    "label": "CAS Server",
    "query": "label_values(cas_build_info{namespace=~\"$namespace\"},cas_server)"
   }
  ]
 },
 "panels": [
  {
   "title": "CAS Server Info",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(cas_build_info{namespace=~\"$namespace\",cas_server=~\"$casServer\"} + on (cas_server,namespace) group_left(name,release,system,version) cas_os_info{namespace=~\"$namespace\",cas_server=~\"$casServer\"}) + on (cas_server, namespace) group_left(state) cas_grid_state{namespace=~\"$namespace\",cas_server=~\"$casServer\"}"
    }
   ]
  },
  {
   "title": "Current Sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cas_grid_sessions_current{namespace=~\"$namespace\",cas_server=~\"$casServer\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "format": "clocks",
   "valueName": "current",
   "targets": [
    {
     "expr": "cas_grid_uptime_seconds_total{namespace=~\"$namespace\",cas_server=~\"$casServer\"}"
    }
   ]
  },
  {
   "title": "CPU by Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cas_node_cpu_time_seconds{namespace=~\"$namespace\",cas_server=~\"$casServer\",type=~\"user|system\"}[1m])) by (cas_node)",
     "legendFormat": "{{cas_node}}"
    }
   ]
  },
  {
   "title": "Memory by Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Physical" }
   ],
   "targets": [
    {
     "expr": "(cas_node_mem_size_bytes{namespace=~\"$namespace\",cas_server=~\"$casServer\",type=\"physical\"}-cas_node_mem_free_bytes{namespace=~\"$namespace\",cas_server=~\"$casServer\",type=\"physical\"})",
     "legendFormat": "{{cas_node}}"
    }
   ]
  },
  {
   "title": "Total CPU by Node Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum by (cas_node_type) (rate(cas_node_cpu_time_seconds{namespace=~\"$namespace\",cas_server=~\"$casServer\",type=~\"user|system\"}[1m]))",
     "legendFormat": "{{cas_node_type}}s"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cas_node_open_files{namespace=~\"$namespace\",cas_server=~\"$casServer\"}",
     "legendFormat": "{{cas_node}}"
    }
   ]
  }
 ]
}