{
 "title": "SAS Go Service Details",
 "description": "Dashboard for Go-based services",
 "tags": [
  "sas-viya",
  "welcome-viya"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(sas_build_info{sas_service_base=\"golang\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(go_info{sas_service_base=\"golang\",namespace=~\"$namespace\"}, service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(go_info{job=\"$application\",namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sas_build_info{job=~\"$application\", pod=~\"$instance\",version=~\".+\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{job=~\"$application\", pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"$instance\",job=~\"$application\"}"
    }
   ]
  },
  {
   "title": "Service Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$application\", pod=~\"$instance\"}[1m])",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"$instance\",job=~\"$application\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{job=~\"$application\", pod=~\"$instance\"}",
     "legendFormat": "live"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(log_events_total{job=~\"$application\", pod=~\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\", job=~\"$application\", pod=~\"$instance\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sas_db_pool_connections{service=~\"$application\",pod=~\"$instance\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sas_db_connections_max{service=~\"$application\",pod=~\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Closed Connections by Reason",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sas_db_closed_total{job=~\"$application\", pod=~\"$instance\"}[1m])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$application\", pod=~\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{job=~\"$application\", pod=~\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}