{
 "title": "SAS Arke Dashboard",
 "tags": [ "sas-viya" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(arke_request_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Arke Events Consumed/Produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(arke_client_consumed{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(rate(arke_client_produced{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "In-Flight Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(arke_client_active_messages{namespace=\"$namespace\"})",
     "legendFormat": "In flight"
    }
   ]
  },
  {
   "title": "Arke Events Consumed by Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(arke_client_consumed{namespace=\"$namespace\"}[$__rate_interval]) > 0",
     "legendFormat": "{{ClientIdentifier}}"
    }
   ]
  }
 ]
}