{
 "title": "SAS Micro Analytic Service",
 "tags": [
  "sas-micro-analytic-service",
  "sas-viya"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "module",
    "query": {
     "query": "label_values(mas_module_execution_seconds_count,module)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "client_id",
    "query": {
     "query": "label_values(mas_module_execution_seconds_count, client_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Throughput Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request vs Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mas_module_execution_seconds_count{module=\"$module\", client_id=~\"$client_id\"}[$interval]))",
     "legendFormat": "TPS"
    },
    {
     "expr": "sum(mas_module_execution_seconds_max{module=\"$module\", client_id=~\"$client_id\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Max TPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(mas_module_execution_seconds_count{module=\"$module\", client_id=~\"$client_id\"}[$interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(mas_module_execution_seconds_count{module=\"$module\", client_id=~\"$client_id\"}[$interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Average TPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mas_module_execution_seconds_count{module=\"$module\", client_id=~\"$client_id\"}[$interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(mas_module_execution_seconds_max{module=\"$module\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "Current Latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mas_module_execution_seconds_max{module=\"$module\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mas_module_execution_seconds_max{module=\"$module\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "Module Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mas_module_execution_seconds_count{module=\"$module\", client_id=~\"$client_id\"}[$interval])",
     "legendFormat": "{{module}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "The average latency for all execution calls to the module.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mas_module_execution_seconds_sum{module=\"$module\", client_id=~\"$client_id\"}[$interval])/rate(mas_module_execution_seconds_count{module=\"$module\", client_id=~\"$client_id\"}[$interval]) ",
     "legendFormat": "{{module}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Module Called Time Range",
   "type": "timeseries",
   "description": "The number of times that a module was called within the pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mas_module_execution_seconds_count{module=\"$module\", client_id=~\"$client_id\"}",
     "legendFormat": "{{module}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "description": "The request with the maximum latency for the given time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "mas_module_execution_seconds_max{module=\"$module\", client_id=~\"$client_id\"}",
     "legendFormat": "{{module}} {{client_id}}"
    }
   ]
  },
  { "title": "Score Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Average Output Score",
   "type": "timeseries",
   "description": "The average output score over a period of time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mas_module_score_count{module=\"$module\", client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{module}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Max Output Score",
   "type": "timeseries",
   "description": "The max output score over a period of time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mas_module_score_max{module=\"$module\", client_id=~\"$client_id\"}",
     "legendFormat": "{{module}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Pod Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SAS Micro Analytic Service Memory",
   "type": "stat",
   "description": "Current memory that is used by the SAS Micro Analytic Service core component.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mas_core_memoryused" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{pod=~\"sas-microanalytic.*\"})"
    }
   ]
  },
  {
   "title": "Pod Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_rss{pod=~\"sas-microanalytic-score.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Modules Called",
   "type": "table",
   "description": "The total number of times that a module was called.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (module) (mas_module_execution_seconds_count{client_id=~\"$client_id\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Loaded Modules",
   "type": "table",
   "description": "All loaded modules.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "targets": [
    { "expr": "mas_module_availability", "legendFormat": "{{module}}" }
   ]
  }
 ]
}