apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit-v2
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  endpoints:
  - path: /api/v1/metrics/prometheus
    port: http
    # Add 'node' label for a hostname instead of just an IP address
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  namespaceSelector:
    any: true
    # Optional: change 'any' to 'false' above to limit namespace(s)
    # matchNames:
    # - logging
