# Sample: contour/host-based-ingress Version: 0.2.2


# This sample does NOT make the OpenSearch API endpoint accessible
# by default because there are limited use-cases for which this
# would be required.  However, if needed, you can make the
# OpenSearch API accessible by creating an HTTPProxy resource for
# it using this sample file.

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-search
spec:
  virtualhost:
    fqdn: search.host.cluster.example.com
    tls:
      secretName: v4m-ingress-tls-secret
  routes:
    - conditions:
      - prefix: /
      services:
        - name: v4m-search
          port: 9200
          protocol: tls

