# Place overrides for the Prometheus Operator Helm Chart Here

# Prometheus Operator Helm Chart
# https://https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
#
# CRDs
# https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md
#
# Default Values
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

# This sample demonstrates path-based ingress

# NOTE: Edit hostnames and ingress port

prometheus:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: true
    hosts:
    - host.mycluster.example.com
  prometheusSpec:
    routePrefix: /prometheus
    externalUrl: http://host.mycluster.example.com/prometheus

alertmanager:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: true
    hosts:
    - host.mycluster.example.com
    paths:
    - /alertManager
  alertmanagerSpec:
    routePrefix: /alertManager
    externalUrl: http://host.mycluster.example.com/alertManager

grafana:
  # Additional configuration necessary to serve Grafana from a subpath
  "grafana.ini":
    server:
      protocol: http
      domain: host.mycluster.example.com
      root_url: http://host.mycluster.example.com/grafana
      serve_from_sub_path: true
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: true
    hosts:
    - host.mycluster.example.com
    path: /grafana
  