prometheus:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  # Define host-based ingress
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx  
    enabled: true
    hosts:
    - prometheus.host.mycluster.example.com
  prometheusSpec:
    externalUrl: https://prometheus.host.mycluster.example.com

alertmanager:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  # Define host-based ingress
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx  
    enabled: true
    hosts:
    - alertmanager.host.mycluster.example.com
  alertManagerSpec:
    externalUrl: https://alertmanager.host.mycluster.example.com

grafana:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  # Define host-based ingress
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - grafana.host.mycluster.example.com
