ingress:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: dashboards.logging.host.cluster.example.com
      paths:
        - path: /
          backend:
            serviceName: v4m-osd
            servicePort: 443
  tls:
    - secretName: kibana-ingress-tls-secret
      hosts:
        - dashboards.logging.host.cluster.example.com
