ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  enabled: true
    # ingressClassName is not currently supported by the Open Distro helm chart
    # ingressClassName: nginx
  hosts:
    - host: kibana.logging.host.cluster.example.com
      paths:
        - path: /
          backend:
            serviceName: v4m-osd
            servicePort: 443
  tls:
    - secretName: kibana-ingress-tls-secret
      hosts:
        - kibana.logging.host.cluster.example.com
