apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eventrouter
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  selector:
    matchLabels:
      kubernetes.io/name: eventrouter
  namespaceSelector:
    any: true
    # Optional: change 'any' to 'false' above to limit namespace(s)
    # matchNames:
    # - logging
  podMetricsEndpoints:
  - relabelings:
    - sourceLabels: [__meta_kubernetes_pod_ip]
      regex: (.*)
      action: replace
      targetLabel: __address__
      replacement: $1:8080
