apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: v4m-prometheus-__TENANT__-tls-cert
  labels:
    v4m.sas.com/tenant: __TENANT__
    sas.com/monitoring-base: kube-viya-monitoring
spec:
  commonName: v4m-prometheus-__TENANT__
  dnsNames:
  - localhost
  - v4m-prometheus-__TENANT__
  issuerRef:
    kind: Issuer
    name: sas-viya-issuer
  secretName: v4m-prometheus-__TENANT__-tls-secret
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
