# Default values: https://github.com/heptiolabs/eventrouter/blob/master/yaml/eventrouter.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter
  namespace: "__LOG_NS__"
  labels:
    v4m.sas.com/name: viya4-monitoring-kubernetes
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventrouter
  labels:
    v4m.sas.com/name: viya4-monitoring-kubernetes
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventrouter
  labels:
    v4m.sas.com/name: viya4-monitoring-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventrouter
subjects:
- kind: ServiceAccount
  name: eventrouter
  namespace: "__LOG_NS__"
---
apiVersion: v1
data:
  config.json: |-
    {
      "sink": "stdout"
    }
kind: ConfigMap
metadata:
  name: eventrouter-cm
  namespace: "__LOG_NS__"
  labels:
    v4m.sas.com/name: viya4-monitoring-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrouter
  namespace: "__LOG_NS__"
  labels:
    kubernetes.io/name: eventrouter
    app: eventrouter
    v4m.sas.com/name: viya4-monitoring-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventrouter
  template:
    metadata:
      labels:
        kubernetes.io/name: eventrouter
        app: eventrouter
        tier: control-plane-addons
        v4m.sas.com/name: viya4-monitoring-kubernetes
    spec:
      containers:
        - name: kube-eventrouter
          image: __EVENTROUTER_REGISTRY__/heptio-images/eventrouter:v0.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter
      imagePullSecrets:
        - name: __PULL_SECRET_NAME__
      serviceAccount: eventrouter
      automountServiceAccountToken: true
      volumes:
        - name: config-volume
          configMap:
            name: eventrouter-cm
