apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    sas.com/monitoring-base: kube-viya-monitoring
  name: sas-launcher-job-rules
spec:
  groups:
  - name: sas-launcher-job-info.rules
    interval: 6s
    rules:
    - expr: sum((label_replace(kube_pod_labels{label_sas_com_created_by="sas-launcher"},"job_pod","$1","pod","(.+)") * on (job_pod) group_left(job_name,queue_name) sas_job_info{}) * on (pod) group_left(node) kube_pod_info{}) without (container, endpoint, instance, job, service)
      record: ':sas_launcher_pod_info:'
    - expr: sum(:sas_launcher_pod_info:* on (namespace, pod) group_left(phase) (kube_pod_status_phase{}==1)) without (endpoint,instance,job,service)
      record: ':sas_launcher_pod_status:'
  - name: sas-launcher-job-metrics.rules
    interval: 10s
    rules:
    - expr: :sas_launcher_pod_status:{phase="Running"} * on (namespace,pod) group_left sum(rate(container_cpu_usage_seconds_total{container="",cpu="total"}[1m])) by (namespace,pod)
      record: ':sas_launcher_pod_cpu_core_usage:'
    - expr: :sas_launcher_pod_status:{phase="Running"} * on (namespace,pod) group_left sum(container_memory_working_set_bytes{container=""}) by (namespace,pod)
      record: ':sas_launcher_pod_mem_working_set_bytes:'
    - expr: :sas_launcher_pod_status:{phase="Running"} * on (namespace,pod) group_left sum(container_memory_usage_bytes{container=""}) by (namespace,pod)
      record: ':sas_launcher_pod_mem_usage_bytes:'
    - expr: :sas_launcher_pod_status:{phase="Running"} * on (namespace,pod) group_left sum(container_fs_reads_bytes_total{container!=""}) by (namespace,pod)
      record: ':sas_launcher_pod_fs_read_bytes_total:'
    - expr: :sas_launcher_pod_status:{phase="Running"} * on (namespace,pod) group_left sum(container_fs_writes_bytes_total{container!=""}) by (namespace,pod)
      record: ':sas_launcher_pod_fs_write_bytes_total:'
    - expr: :sas_launcher_pod_status:{phase="Running"} * on (namespace,pod) group_left sum(container_network_receive_bytes_total{}) by (namespace,pod)
      record: ':sas_launcher_pod_net_receive_bytes_total:'
    - expr: :sas_launcher_pod_status:{phase="Running"} * on (namespace,pod) group_left sum(container_network_transmit_bytes_total{}) by (namespace,pod)
      record: ':sas_launcher_pod_net_transmit_bytes_total:'
