{
 "title": "EPD / Kubernetes Pods",
 "tags": [ "kubernetes-cluster" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Use  (using rules metrics)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "{{pod}} - Req"
    },
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "{{pod}} - Lim"
    },
    {
     "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "{{ pod }} - % of Limit"
    },
    {
     "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))",
     "legendFormat": "{{pod}} - Use"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__range]))",
     "legendFormat": "{{pod}} - Avg"
    },
    {
     "expr": "(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__range]))",
     "legendFormat": "{{pod}} - Max"
    }
   ]
  },
  {
   "title": "Memory Use  bytes  (using rules metrics)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{pod}} - Req"
    },
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{pod}} - Lim"
    },
    {
     "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r / sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{ pod }} % of Limit"
    },
    {
     "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r",
     "legendFormat": "{{pod}} - Use"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
     "legendFormat": "{{pod}} - AvgWss"
    },
    {
     "expr": "(max_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
     "legendFormat": "{{pod}} - MaxWss"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_memory_cache{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
     "legendFormat": "{{pod}} - AvgCache"
    },
    {
     "expr": "(max_over_time(node_namespace_pod_container:container_memory_cache{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
     "legendFormat": "{{pod}} - MaxCache"
    }
   ]
  },
  {
   "title": "CPU    (time series aggregations)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory    (time series aggregations)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes           {job=\"kubelet\"           , namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU use/req/lim (sum across containers)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum  (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "sum  (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=\"$namespace\"})\r",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "sum  (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=\"$namespace\"})\r",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "MEM use/cache/req/lim (sum across containers)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum  (container_memory_usage_bytes{job=\"kubelet\", namespace=\"$namespace\", container!=\"POD\"})\r",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "sum  (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=\"$namespace\"})\r",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "sum  (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=\"$namespace\"})\r",
     "legendFormat": "Limit: {{ container }}"
    },
    {
     "expr": "sum  (container_memory_cache{job=\"kubelet\", namespace=\"$namespace\", container!=\"POD\"})\r",
     "legendFormat": "Cache: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU use (per container)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "Current: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "MEM use (per container)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "Current: {{ container }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU use/req/lim (per container)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "Current: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"})\r",
     "legendFormat": "Requested: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"})\r",
     "legendFormat": "Limit: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "MEM use/cache/req/lim (per container)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "Current: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"                  })\r",
     "legendFormat": "Requested: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"                  })\r",
     "legendFormat": "Limit: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (container_memory_cache{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "Cache: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\"}[4m])))",
     "legendFormat": "RX: {{ pod }}"
    },
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$pod\"}[4m])))",
     "legendFormat": "TX: {{ pod }}"
    }
   ]
  },
  {
   "title": "Total Restarts Per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod,container) (kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Restarts: {{pod}}/{{ container }}"
    }
   ]
  }
 ]
}