{
 "title": "EPD / Node Utilization",
 "tags": [ "kubernetes-cluster" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(up{job=\"node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_cpu_utilisation:rate1m{job=\"node-exporter\", instance=~\"$instance\"}\n*\n  instance:node_num_cpu:sum{job=\"node-exporter\", instance=~\"$instance\"}\n/ ignoring (instance) group_left\n  sum without (instance) (instance:node_num_cpu:sum{job=\"node-exporter\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "CPU Saturation (load1 per CPU)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_load1_per_cpu:ratio{job=\"node-exporter\", instance=~\"$instance\"}\n/ ignoring (instance) group_left\n  count without (instance) (instance:node_load1_per_cpu:ratio{job=\"node-exporter\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=~\"$instance\"}\n/ ignoring (instance) group_left\n  count without (instance) (instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "instance:node_vmstat_pgmajfault:rate1m{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Net Utilization (Bytes Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Net Saturation (Drops Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate1m{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate1m{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance_device:node_disk_io_time_seconds:rate1m{job=\"node-exporter\", instance=~\"$instance\"}\n/ ignoring (instance, device) group_left\n  count without (instance, device) (instance_device:node_disk_io_time_seconds:rate1m{job=\"node-exporter\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{instance}} {{device}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance_device:node_disk_io_time_weighted_seconds:rate1m{job=\"node-exporter\", instance=~\"$instance\"}\n/ ignoring (instance, device) group_left\n  count without (instance, device) (instance_device:node_disk_io_time_weighted_seconds:rate1m{job=\"node-exporter\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{instance}} {{device}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Space Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without (device) (\n    max without (fstype, mountpoint) (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"\"} - node_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"\"}\n    )\n  ) \n/ ignoring (instance) group_left\n  sum without (instance, device) (\n    max without (fstype, mountpoint) (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"\"}\n    )\n  )\n)  \n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without (device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"\"} - node_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"\"}\n    )\n  ) \n/ ignoring (instance) group_left\n  sum without (instance, device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"\"}\n    )\n  )\n)  \n",
     "legendFormat": "{{instance}} - {{mountpoint}}    ({{fstype}})",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  }
 ]
}