{
 "title": "EPD / Kubernetes Headroom",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Allocatable CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory(GB)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})\r)"
    }
   ]
  },
  {
   "title": "Total Allocatable Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{})"
    }
   ]
  },
  {
   "title": "Total Allocatable CPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"}) - sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"})\r"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory(GB) Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"}) - sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"})\r)"
    }
   ]
  },
  {
   "title": "Total Allocatable Pods Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{}) - sum(kubelet_running_pod_count{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"})\r"
    }
   ]
  },
  {
   "title": "% Allocatable CPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * (sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"}) - sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"})) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "% Allocatable Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"}) - sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"})\r)/sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "% Allocatable Pods Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * (sum(kube_node_status_allocatable_pods{}) - sum(kubelet_running_pod_count{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"})) / sum(kube_node_status_allocatable_pods{})\r"
    }
   ]
  },
  {
   "title": "Resources by Namespace",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "cpu req"
    },
    {
     "expr": "1/1000000000*sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "GB mem req"
    },
    {
     "expr": "count(mixin_pod_workload{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Resources by Node",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"}) by (node)",
     "legendFormat": "Pod Count"
    },
    {
     "expr": "sum(kube_node_status_allocatable_pods{}) by (node)",
     "legendFormat": "Pods Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{})\r by (node)",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{}) by (node)",
     "legendFormat": "CPU Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{}) by (node)",
     "legendFormat": "Mem Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{}) by (node)",
     "legendFormat": "Mem Allocatable"
    }
   ]
  }
 ]
}