{
 "title": "Perf / Container Utilization",
 "tags": [
  "kubernetes-cluster",
  "welcome-cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "statefulset",
    "label": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_labels{namespace=~\"$namespace\"}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main graphs & charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "nginx_ingress_controller_requests (hits/second) by namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (exported_namespace) (irate(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\",  service=~\"$container\"}[1m])))\n",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "nginx_ingress_controller_requests (hits/second) by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (service) (irate(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\",  service=~\"$container\"}[1m])))\n",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU use",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "{{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "MEM use",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{ container }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Replicas (by HPA)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\"})\r\n",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "Replicas (by Deployment)",
   "type": "graph",
   "description": "does not seem to be as accurate as replica count by HPA...",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$pod\"})\r\n",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Node Count by nodepool",
   "type": "graph",
   "description": "For monitoring Cluster Autoscaling (CA) scale out & scale in",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label_workload_sas_com_class\r) (kube_node_labels{})\n",
     "legendFormat": "{{label_workload_sas_com_class}}"
    }
   ]
  },
  {
   "title": "pod phase count by namespace",
   "type": "graph",
   "description": "For seeing how long it takes viya pods to progress during startup to all pods reaching ContainerReady=true ",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,phase) (kube_pod_status_phase{})",
     "legendFormat": "{{namespace}} pods {{phase}}"
    }
   ]
  },
  {
   "title": "% CPU use / req",
   "type": "graph",
   "description": "100% (consider increasing req)\n0% (sized just right)\n-100% (consider decreasing req)",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})\r ))\n",
     "legendFormat": "cpuUse/req {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "% MEM use / req",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) / sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) ))\r\n",
     "legendFormat": "memUse/req: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "% CPU use / lim",
   "type": "graph",
   "description": "100% (consider increasing req)\n0% (sized just right)\n-100% (consider decreasing req)",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) ))\r",
     "legendFormat": "{{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "% MEM use / lim",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) / sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) ))\r\n",
     "legendFormat": "memUse/req: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\"}[4m])))",
     "legendFormat": "RX: {{ pod }}"
    },
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\"}[4m])))",
     "legendFormat": "TX: {{ pod }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors per Pod -- \"endpoint/sas_service_base/service (node)\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"$namespace\", pod=~\"$pod\"}\r ",
     "legendFormat": "{{endpoint}}/{{sas_service_base}}/{{service}} ({{node}})"
    }
   ]
  },
  {
   "title": "Total Restarts Per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod,container) (kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Restarts: {{pod}}/{{ container }}"
    }
   ]
  },
  {
   "title": "Secondary graphs & charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Use",
     "type": "table-old",
     "description": "NOTE: using rules metrics, and % values are \"current use\" as a % of cpu",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
       "legendFormat": "{{pod}} - Req"
      },
      {
       "expr": "sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
       "legendFormat": "{{pod}} - Lim"
      },
      {
       "expr": "(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__range]))",
       "legendFormat": "{{pod}} - Max"
      },
      {
       "expr": "(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__range]))",
       "legendFormat": "{{pod}} - Avg"
      },
      {
       "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))",
       "legendFormat": "{{pod}} - Use(current)"
      },
      {
       "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
       "legendFormat": "{{ pod }} - % of Req(current)"
      },
      {
       "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
       "legendFormat": "{{ pod }} - % of Lim(current)"
      }
     ]
    },
    {
     "title": "Memory Use  (bytes)",
     "type": "table-old",
     "description": "NOTE: using rules metrics, and % values are \"current use\" as a % of mem",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
       "legendFormat": "{{pod}} - Req"
      },
      {
       "expr": "sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
       "legendFormat": "{{pod}} - Lim"
      },
      {
       "expr": "(max_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
       "legendFormat": "{{pod}} - MaxWss"
      },
      {
       "expr": "(avg_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
       "legendFormat": "{{pod}} - AvgWss"
      },
      {
       "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r",
       "legendFormat": "{{pod}} - Use(current)"
      },
      {
       "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r / sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
       "legendFormat": "{{ pod }} % of Req(current)"
      },
      {
       "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r / sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
       "legendFormat": "{{ pod }} % of Lim(current)"
      }
     ]
    },
    {
     "title": "Total CPU use & req",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum  (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", container!=\"POD\", image!=\"\"}[4m]))\r",
       "legendFormat": "Current: {{ container }}"
      },
      {
       "expr": "sum  (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\"})\r",
       "legendFormat": "Requested: {{ container }}"
      }
     ]
    },
    {
     "title": "Total MEM use & req",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 98 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum  (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", container!=\"POD\"})\r",
       "legendFormat": "Current: {{ container }}"
      },
      {
       "expr": "sum  (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\"})\r",
       "legendFormat": "Requested: {{ container }}"
      }
     ]
    },
    {
     "title": "CPU use, req, lim (edit to enable)",
     "type": "graph",
     "description": "Disabled by default to improve performance. Ideal use is to filter to look at one container at a time with this graph.",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ]
    },
    {
     "title": "MEM use, req, lim, cache (edit to enable)",
     "type": "graph",
     "description": "Disabled by default to improve performance. Ideal use is to filter to look at one container at a time with this graph.",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 105 },
     "yaxes": [
      { "format": "bytes" }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 20, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "process_open_fds{namespace=~\"$namespace\", pod=~\"$pod\"}\r ",
       "legendFormat": "{{endpoint}}/{{sas_service_base}}/{{service}} ({{node}})"
      }
     ]
    }
   ]
  }
 ]
}