{
 "title": "Perf / Analysis",
 "tags": [
  "kubernetes-cluster",
  "welcome-cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "NodeClass",
    "query": {
     "query": "label_values(kube_node_labels,label_workload_sas_com_class)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_labels{label_workload_sas_com_class=~\"$NodeClass\"},node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{exported_nodename=~\"(?i:($Node))\"}, instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "pvc",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}, persistentvolumeclaim)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Bird's Eye View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Is Viya Up?",
   "type": "timeseries",
   "description": "watch the sas-readiness container to see when viya begins starting up (container exists but ready=0), and viya startup complete (ready=1)\n\nalso including container restarts in this graph\n",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container,pod) (kube_pod_container_status_ready{namespace=~\"$namespace\", container=\"sas-readiness\"})",
     "legendFormat": "VIYA_UP({{container}})"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])",
     "legendFormat": "restarts({{container}})"
    }
   ]
  },
  {
   "title": "Autoscaling (Pods & Nodes)",
   "type": "timeseries",
   "description": "Pod replicas \"scheduled\" lags behind \"desired\" due to node startup time (this is normal).  \n",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "# HPA pod replicas desired ({{namespace}})\r\nsum by(namespace) (kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\"})",
     "legendFormat": "HPA pod replicas desired ({{namespace}})"
    },
    {
     "expr": "# HPA pod replicas ready ({{namespace}})\r\nsum by(namespace) (kube_deployment_status_replicas_available{\r\n    namespace=~\"$namespace\"\r\n  , deployment=~\"$pod\"\r\n  , deployment!=\"sas-opendistro-operator\"\r\n  , deployment!=\"sas-readiness\"\r\n  , deployment!=\"sas-prepull\"\r\n  , deployment!=\"sas-data-server-utility\"\r\n  , deployment!=\"sas-connect-spawner\"\r\n  , deployment!~\"sas-crunchy-data-postgres.*\"\r\n  , deployment!=\"sas-connect-spawner\"\r\n  , deployment!=\"sas-config-reconciler\"\r\n  , deployment!=\"sas-cas-operator\"\r\n  , deployment!=\"prometheus-pushgateway\"\r\n  , deployment!=\"sas-data-server-operator\"\r\n})",
     "legendFormat": "HPA pod replicas ready ({{namespace}})"
    },
    {
     "expr": "# nodepool: {{label_agentpool}}\r\n(sum by (label_agentpool) (kube_node_labels{node=~\"$Node\", node=~\".*$NodeClass.*\"}))",
     "legendFormat": "nodepool: {{label_agentpool}}"
    }
   ]
  },
  {
   "title": "Container CPU (% of request)",
   "type": "timeseries",
   "description": "If container xyz is hitting 100% of its CPU request, then it's a performance bottleneck. Increase its request (and possibly the size of the node it is on) and it should run faster.",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 100 * (\nsum by(pod,container) (irate(container_cpu_usage_seconds_total{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) \n/ \nsum by(pod,container) (kube_pod_container_resource_requests{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) \n))\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100*(\n  sum by(pod,container) (irate(container_cpu_usage_seconds_total {node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"kubelet\", container!=\"POD\", image!=\"\"}[4m])) \n/ sum by(pod,container) (      kube_pod_container_resource_limits{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"kube-state-metrics\", resource=\"cpu\"  }    )\n))\n# {{container}}\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Node CPU Util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"})\n)",
     "legendFormat": "{{nodename}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Node Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (nodename,device) (rate(node_network_receive_bytes_total{job=\"node-exporter\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\", device!=\"lo\", device!~\"veth.*\", device!~\"en.*\"}[$__rate_interval]) )",
     "legendFormat": "Rx: {{nodename}} ({{device}})",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "sum by (nodename,device) (rate(node_network_transmit_bytes_total{job=\"node-exporter\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\", device!=\"lo\", device!~\"veth.*\", device!~\"en.*\"}[$__rate_interval]) )",
     "legendFormat": "Tx: {{nodename}} ({{device}})",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Container Memory (rss)  (% of request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 100 * (\nsum by(pod,container) (container_memory_rss{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_requests{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\r\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory (rss) (% of limit)",
   "type": "timeseries",
   "description": "If near 100% then processes in the container are at risk of OutOfMemory exception",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 100 * (\nsum by(pod,container) (container_memory_rss{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_limits{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Node Memory Util (rss+dirty)",
   "type": "timeseries",
   "description": "rss +  dirty pages (in cache but not safe to reclaim / flush from mem due to not yet being written to disk)",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# graph1: total-available ~= memrss            ... ((total-available)+dirtypages) = memrss+dirtypages\n# graph2: total-free      ~= memrss+cached+buffers  ... ((total-free)+dirtypages) = memrss+dirtypages+cached+buffers\n#( (node_memory_MemTotal_bytes{nodename=~\"$Node\"}-node_memory_MemAvailable_bytes{nodename=~\"$Node\"}) + node_memory_Dirty_bytes{nodename=~\"$Node\"}) / node_memory_MemTotal_bytes{nodename=~\"$Node\"}\nsum by(nodename)(\n    ( (node_memory_MemTotal_bytes{nodename=~\"$Node\"}-node_memory_MemAvailable_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}) + node_memory_Dirty_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}) / node_memory_MemTotal_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}\n)",
     "legendFormat": "{{nodename}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Node Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[1m])) by (nodename,device)",
     "legendFormat": "Read: {{nodename}} ({{device}})",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[1m])) by (nodename,device)",
     "legendFormat": "Write: {{nodename}} ({{device}})",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Container Status Count by Namespace",
   "type": "timeseries",
   "description": "This panel is useful for seeing how long it takes SAS Viya pods to progress during startup to all pods reaching ContainerReady=true ",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_container_status_ready{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}} containers total"
    },
    {
     "expr": "sum by (namespace) (kube_pod_container_status_ready{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}} containers ready"
    },
    {
     "expr": "sum by (namespace) (kube_pod_container_status_waiting{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}} containers waiting"
    },
    {
     "expr": "count by (namespace) (kube_pod_init_container_status_ready{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}} init containers total"
    },
    {
     "expr": "sum by (namespace) (kube_pod_init_container_status_ready{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}} init containers ready"
    },
    {
     "expr": "sum by (namespace) (kube_pod_init_container_status_waiting{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}} init containers waiting"
    }
   ]
  },
  {
   "title": "Node Disk & PVC Storage Use %",
   "type": "timeseries",
   "description": "Two metrics in one graph, both about \"storage use\":\n\n1. node local storage like ext4, xfs\nexcluding tmpfs & fuse.lxcfs\nAlso, switching from filesystem size-available to size-free because this is what df outputs (since freebytes = availbytes + rootreserved, and rootreserved is not really available to users).\n\n2. PVC usage. Warning: PVCs provisioned from Azure NFS server show total NFS server \"/export\" LUN capacity and usage percentages for each PVC, instead of the actual size and usage of each distinct PVC... Not sure (yet) how to get the actual accurate PVC usage metrics.\n",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "( sum without (device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"} \n    - node_filesystem_free_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"}\n    )\n  ) \n/ ignoring (instance) group_left\n  sum without (instance, device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"}\n    )\n  )\n)  \n",
     "legendFormat": "fs({{fstype}}) - {{nodename}}:{{mountpoint}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "# PVC: {{persistentvolumeclaim}}\r\n# pvc({{persistentvolumeclaim}}) - ns({{namespace}})\r\n( kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"} \r\n- kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"})\r\n/ kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"}",
     "legendFormat": "pvc({{persistentvolumeclaim}}) - ns({{namespace}})"
    }
   ]
  },
  {
   "title": "Container Memory (tot)  (% of request)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 100 * (\nsum by(pod,container) (container_memory_usage_bytes{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_requests{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory (tot)  (% of limit)",
   "type": "timeseries",
   "description": "If near 100% then processes in the container are at risk of OutOfMemory exception",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 100 * (\nsum by(pod,container) (container_memory_usage_bytes{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_limits{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Node Memory Util (tot) ",
   "type": "timeseries",
   "description": "memory use (including filecache) which can easily  reach 100% due to natural caching of any files opened in order to speed up any subsequent re-open.",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# available - free = cached... fixing by changing this \"total mem use (rss+cache)\" to just MemAvailable\r\n# graph1: total-available ~= memrss            ... ((total-available)+dirtypages) = memrss+dirtypages\r\n# graph2: total-free      ~= memrss+cached+buffers\r\n# ( (node_memory_MemTotal_bytes{nodename=~\"$Node\"}-node_memory_MemFree_bytes{nodename=~\"$Node\"}) ) / node_memory_MemTotal_bytes{nodename=~\"$Node\"}\r\nsum by(nodename)(\r\n    ( (node_memory_MemTotal_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}-node_memory_MemFree_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}) ) / node_memory_MemTotal_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}\r\n)",
     "legendFormat": "{{nodename}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "CAS Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "#{{cas_server}}, {{pod}}, {{container}}, {{service}}, {{endpoint}}, {{instance}}\r\n(cas_grid_sessions_current{namespace=~\"$namespace\",service=~\".+-client\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (nodename) (\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"})\n)",
       "legendFormat": "{{nodename}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Node Memory Util (rss+dirty)",
     "type": "timeseries",
     "description": "rss +  dirty only, filecache not included. dirty is kind of like lazy write bytes that not yet been written to disk so its not safe to flush them out of filecache yet.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# graph1: total-available ~= memrss            ... ((total-available)+dirtypages) = memrss+dirtypages\n# graph2: total-free      ~= memrss+cached+buffers  ... ((total-free)+dirtypages) = memrss+dirtypages+cached+buffers\n( (node_memory_MemTotal_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}-node_memory_MemAvailable_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}) + node_memory_Dirty_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"})\n/ node_memory_MemTotal_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}",
       "legendFormat": "{{nodename}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Node Memory Util (totalMemUse%, rss+cache+buffers)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# available - free = cached... fixing by changing this \"total mem use (rss+cache)\" to just MemAvailable\r\n# graph1: total-available ~= memrss            ... ((total-available)+dirtypages) = memrss+dirtypages\r\n# graph2: total-free      ~= memrss+cached+buffers\r\n( (node_memory_MemTotal_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}-node_memory_MemFree_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}) )\r\n/ node_memory_MemTotal_bytes{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}",
       "legendFormat": "{{nodename}} totalMemUse",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    }
   ]
  },
  {
   "title": "Node CPU (detail)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Utilization (user+nice)",
     "type": "timeseries",
     "description": "user+nice cpu time",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(   sum by(nodename) ( irate( node_cpu_seconds_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\",mode=\"user\"}[1m] ) ) \r\n  + sum by(nodename) ( irate( node_cpu_seconds_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\", mode=\"nice\"}[1m] ) )\r\n) / sum(irate(node_cpu_seconds_total[1m])) by(nodename)\r\n",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Node CPU Utilization (system)",
     "type": "timeseries",
     "description": "system+irq+softirq",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(   sum by(nodename) ( irate( node_cpu_seconds_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\",mode=\"system\"}[1m] ) ) \r\n  + sum by(nodename) ( irate( node_cpu_seconds_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\", mode=\"irq\"}[1m] ) )\r\n  + sum by(nodename) ( irate( node_cpu_seconds_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\", mode=\"softirq\"}[1m] ) )\r\n) / sum(irate(node_cpu_seconds_total[1m])) by(nodename)\r\n",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Node CPU Utilization (iowait)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(   sum by(nodename) ( irate( node_cpu_seconds_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\",mode=\"iowait\"}[1m] ) ) \r\n) / sum(irate(node_cpu_seconds_total[1m])) by(nodename)\r\n",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Container CPU Use",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod,container) (irate(container_cpu_usage_seconds_total{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))\r\n",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Container Memory Use (rss)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod,container) (container_memory_rss{node=~\"$Node\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", pod!~\".*prepull.*\", container=~\"$container\", container!=\"\", container!=\"POD\", container!=\"\"})\r\n",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory Use (tot)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod,container) (container_memory_usage_bytes{node=~\"$Node\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", pod!~\".*prepull.*\", container=~\"$container\", container!=\"\", container!=\"POD\", container!=\"\"})\r\n",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Utilization (% of Request)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Container CPU use as a % of request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( 100 * (\nsum by(pod,container) (irate(container_cpu_usage_seconds_total{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) \n/ \nsum by(pod,container) (kube_pod_container_resource_requests{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) \n))\n",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory use (rss) as a % of request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( 100 * (\nsum by(pod,container) (container_memory_rss{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_requests{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\n",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory use (tot) as a % of request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( 100 * (\nsum by(pod,container) (container_memory_usage_bytes{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_requests{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\r\n",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Utilization (% of Limit)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Container CPU use as a % of limit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( 100 * (\nsum by(pod,container) (irate(container_cpu_usage_seconds_total{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) \n/ \nsum by(pod,container) (kube_pod_container_resource_limits{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) \n))\n",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory use (rss) as a % of limit",
     "type": "timeseries",
     "description": "If near 100% then processes in the container are at risk of OutOfMemory exception or oom killer",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( 100 * (\nsum by(pod,container) (container_memory_rss{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_limits{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\n",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory use (tot) as a % of limit",
     "type": "timeseries",
     "description": "If near 100% then processes in the container are at risk of OutOfMemory exception",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( 100 * (\nsum by(pod,container) (container_memory_usage_bytes{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) \n/ \nsum by(pod,container) (kube_pod_container_resource_limits{node=~\"$Node\", container!=\"\", pod!~\".*prepull.*\", job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) \n))\n",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Net Utilization (by node/interface)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (nodename,device) (rate(node_network_receive_bytes_total{job=\"node-exporter\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\", device!=\"lo\", device!~\"veth.*\"}[$__rate_interval]) )",
       "legendFormat": "Receive: {{nodename}} ({{device}})",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      },
      {
       "expr": "sum by (nodename,device) (rate(node_network_transmit_bytes_total{job=\"node-exporter\", nodename=~\"$Node\", nodename=~\".*$NodeClass.*\", device!=\"lo\", device!~\"veth.*\"}[$__rate_interval]) )",
       "legendFormat": "Transmit: {{nodename}} ({{device}})",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Network packets/second (per node) - inbound (Rx) & outbound (Tx)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 11, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (node,device) (irate(container_network_receive_packets_total{node=~\"$Node\", node=~\".*$NodeClass.*\", namespace=\"\", interface!=\"lo\", interface!~\"veth.*\"}[$__rate_interval]) )",
       "legendFormat": "Rx-Node: {{node}} / {{interface}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      },
      {
       "expr": "(irate(container_network_transmit_packets_total{node=~\"$Node\", node=~\".*$NodeClass.*\", namespace=\"\", interface!=\"lo\", interface!~\"veth.*\"}[$__rate_interval]) )",
       "legendFormat": "Tx-Node: {{node}} / {{interface}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node Disk Throughput",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[1m])) by (nodename,device)",
       "legendFormat": "Read: {{nodename}} ({{device}})",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[1m])) by (nodename,device)",
       "legendFormat": "Write: {{nodename}} ({{device}})",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Node Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[1m]) ",
       "legendFormat": "Read: {{nodename}} ({{device}})"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}[1m]) ",
       "legendFormat": "Write: {{nodename}} ({{device}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "node_sockstat_*",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}",
       "legendFormat": "{{nodename}} (used)"
      },
      {
       "expr": "node_sockstat_TCP_alloc{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}",
       "legendFormat": "{{nodename}} (TCP_alloc)"
      },
      {
       "expr": "node_sockstat_TCP_inuse{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}",
       "legendFormat": "{{nodename}} (TCP_inuse)"
      },
      {
       "expr": "node_sockstat_TCP_tw{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}",
       "legendFormat": "{{nodename}} (TCP_tw)"
      }
     ]
    },
    {
     "title": "node_netstat_Tcp_CurrEstab",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{nodename=~\"$Node\", nodename=~\".*$NodeClass.*\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Capacity Used %",
     "type": "timeseries",
     "description": "Node local storage (e.g. ext4, xfs, etc.) excluding tmpfs & fuse.lxcfs\n\nUses (filesystem size-free) to be comparable to Linux df outputs.",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "( sum without (device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"} \n    - node_filesystem_free_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"}\n    )\n  ) \n/ ignoring (instance) group_left\n  sum without (instance, device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"}\n    )\n  )\n)  \n",
       "legendFormat": "fs({{fstype}}) - {{nodename}}:{{mountpoint}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "PVC Usage %",
     "type": "timeseries",
     "description": "Warning: PVCs provisioned from Azure NFS server show total NFS server \"/export\" LUN capacity and usage percentages for each PVC, instead of the actual size and usage of each distinct PVC",
     "gridPos": { "h": 12, "w": 12, "x": 11, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# PVC: {{persistentvolumeclaim}}\r\n# pvc({{persistentvolumeclaim}}) - ns({{namespace}})\r\n( kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"} \r\n- kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"})\r\n/ kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"}",
       "legendFormat": "pvc({{persistentvolumeclaim}}) - ns({{namespace}})"
      }
     ]
    },
    {
     "title": "Disk Capacity Used",
     "type": "timeseries",
     "description": "Node local storage (e.g. ext4, xfs, etc.) excluding tmpfs & fuse.lxcfs\n\nUses (filesystem size-free) to be comparable to Linux df outputs.",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "( sum without (device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"} \n    - node_filesystem_free_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"}\n    )\n  ) \n#/ ignoring (instance) group_left\n#  sum without (instance, device) (\n#    max without () (\n#      node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\", nodename=~\".*$NodeClass.*\"}\n#    )\n#  )\n)  \n",
       "legendFormat": "fs({{fstype}}) - {{nodename}}:{{mountpoint}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "PVC Usage",
     "type": "timeseries",
     "description": "Warning: PVCs provisioned from Azure NFS server show total NFS server \"/export\" LUN capacity and usage percentages for each PVC, instead of the actual size and usage of each distinct PVC",
     "gridPos": { "h": 12, "w": 12, "x": 11, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "# PVC: {{persistentvolumeclaim}}\r\n# pvc({{persistentvolumeclaim}}) - ns({{namespace}})\r\n( kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"} \r\n- kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"})\r\n#/ kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\", node=~\".*$NodeClass.*\"}",
       "legendFormat": "pvc({{persistentvolumeclaim}}) - ns({{namespace}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "db connections active (total)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "  ( sum by (namespace) (sas_db_pool_connections{container=~\"$container\", pod=~\"$pod\", node=~\"$Node\"}) )\n+ ( sum by (namespace) (jdbc_connections_active{container=~\"$container\", pod=~\"$pod\", node=~\"$Node\"}) )",
       "legendFormat": "db connections: ns={{namespace}}: TOTAL (go+java)"
      },
      { "expr": "pg_settings_max_connections", "legendFormat": "pg_settings_max_connections" },
      {
       "expr": "  ( sum by (namespace,sas_service_base) (sas_db_pool_connections{container=~\"$container\", pod=~\"$pod\", node=~\"$Node\"}) )",
       "legendFormat": "db connections: ns={{namespace}}: {{sas_service_base}}"
      },
      {
       "expr": " ( sum by (namespace,sas_service_base) (jdbc_connections_active{container=~\"$container\", pod=~\"$pod\", node=~\"$Node\"}) )",
       "legendFormat": "db connections: ns={{namespace}}: {{sas_service_base}}"
      }
     ]
    },
    {
     "title": "db connections active (by container)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace,container,sas_service_base) (sas_db_pool_connections{container=~\"$container\", pod=~\"$pod\", node=~\"$Node\"})",
       "legendFormat": "{{namespace}}: {{container}} ({{sas_service_base}})"
      },
      {
       "expr": "sum by (namespace,container,sas_service_base) (jdbc_connections_active{container=~\"$container\", pod=~\"$pod\", node=~\"$Node\"})",
       "legendFormat": "{{namespace}}: {{container}} ({{sas_service_base}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Autoscaler (Azure AKS Only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "ClusterAutoscaler Trigger: Average(%Request Allocated)  Per Nodepool ",
     "type": "timeseries",
     "description": "if > 80% then scaleUp 1 node ... really if any pod cant find a node to schedule to, this is what triggers scale out of a new node\n\nif < 50% then scaleDown 1 node (for avg req allocation mem & cpu on any given node)\n\n",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (nodeprefix, resource)(\r\n  label_replace ( \r\n    max by(pod, node, resource)( \r\n      kube_pod_container_resource_requests {node=~\"$Node\", node=~\".*$NodeClass.*\"} or\r\n      kube_pod_init_container_resource_requests {node=~\"$Node\", node=~\".*$NodeClass.*\"}\r\n    )\r\n  ,\"nodeprefix\", \"$1\", \"node\", \"(aks-[^-]+).+\")\r\n)\r\n/ sum by (nodeprefix, resource)(\r\n    label_replace ( \r\n      kube_node_status_allocatable {node=~\"$Node\", node=~\".*$NodeClass.*\"}\r\n      ,\"nodeprefix\", \"$1\", \"node\", \"(aks-[^-]+).+\"\r\n    )\r\n  )",
       "legendFormat": "{{nodeprefix}}: {{resource}}"
      }
     ]
    },
    {
     "title": "ClusterAutoscaler Trigger: CPU %Request Allocated Per Node",
     "type": "timeseries",
     "description": "ClusterAutoscaler ScaleUp happens when at least one pod is unable to be scheduled.\n\nClusterAutoscaler ScaleDown happens when  node's cpu AND memory requests/capacity is below the scale-down-utilization-threshold of 50%(default), denoted by the lower blue region\n",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# This query reflects what you see from \"kubectl describe node | grep 'Allocated resources' -A6\r\n#   Divide by \"allocatable\" cpu or memory instead of \"capacity\"\r\n#   Use the highest value for cpu request & memory req from all containers And initContainers in each pod\r\nsum by(node)(\r\n  max by(pod, node, resource)( \r\n    kube_pod_container_resource_requests       {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"cpu\"} or\r\n    kube_pod_init_container_resource_requests  {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"cpu\"} )\r\n) / sum by(node)( kube_node_status_allocatable {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"cpu\"} )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ClusterAutoscaler Trigger: Mem %Request Allocated Per Node",
     "type": "timeseries",
     "description": "ClusterAutoscaler ScaleUp happens when at least one pod is unable to be scheduled.\n\nClusterAutoscaler ScaleDown happens when  node's cpu AND memory requests/capacity is below the scale-down-utilization-threshold of 50%(default), denoted by the lower blue region\n",
     "gridPos": { "h": 9, "w": 7, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# This query reflects what you see from \"kubectl describe node | grep 'Allocated resources' -A6\r\n#   Divide by \"allocatable\" cpu or memory instead of \"capacity\"\r\n#   Use the highest value for cpu request & memory req from all containers And initContainers in each pod\r\nsum by(node)(\r\n  max by(pod, node, resource)( \r\n    kube_pod_container_resource_requests       {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"memory\"} or\r\n    kube_pod_init_container_resource_requests  {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"memory\"} )\r\n) / sum by(node)( kube_node_status_allocatable {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"memory\"} )\r\n",
       "legendFormat": "{{node}}: mem"
      }
     ]
    },
    {
     "title": "ClusterAutoscaler Trigger: %Request Allocated Per Node",
     "type": "table",
     "description": "ClusterAutoscaler ScaleDown should happen for any node in this table with \"blue\" CPU & MEM (i.e. below the scale-down-utilization-threshold of 50%(default)). For more detail -> https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work\n\nIf nodes are not scaling down, then check nodes for Pods with restrictive PodDisruptionBudget, Pods that are not backed by a controller object, etc. For more detail -> https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node\n\n\nClusterAutoscaler ScaleUp happens when at least one pod is unable to be scheduled. Numbers over 80% are colored red to indicate increased chance of not being able to schedule a pod on that node.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# This query reflects what you see from \"kubectl describe node | grep 'Allocated resources' -A6\r\n#   Divide by \"allocatable\" cpu or memory instead of \"capacity\"\r\n#   Use the highest value for cpu request & memory req from all containers And initContainers in each pod\r\nsum by(node)(\r\n  max by(pod, node, resource)( \r\n    kube_pod_container_resource_requests       {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"cpu\"} or\r\n    kube_pod_init_container_resource_requests  {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"cpu\"} )\r\n) / sum by(node)( kube_node_status_allocatable {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"cpu\"} )",
       "legendFormat": "{{node}}: cpu"
      },
      {
       "expr": "# This query reflects what you see from \"kubectl describe node | grep 'Allocated resources' -A6\r\n#   Divide by \"allocatable\" cpu or memory instead of \"capacity\"\r\n#   Use the highest value for cpu request & memory req from all containers And initContainers in each pod\r\nsum by(node)(\r\n  max by(pod, node, resource)( \r\n    kube_pod_container_resource_requests       {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"memory\"} or\r\n    kube_pod_init_container_resource_requests  {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"memory\"} )\r\n) / sum by(node)( kube_node_status_allocatable {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"memory\"} )\r\n",
       "legendFormat": "{{node}}: mem"
      },
      {
       "expr": "# This query reflects what you see from \"kubectl describe node | grep 'Allocated resources' -A6\r\n#   Divide by \"allocatable\" cpu or memory instead of \"capacity\"\r\n#   Use the highest value for cpu request & memory req from all containers And initContainers in each pod\r\nsum by(node)(\r\n  max by(pod, node, resource)( \r\n    kube_pod_container_resource_requests       {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"ephemeral_storage\"} or\r\n    kube_pod_init_container_resource_requests  {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"ephemeral_storage\"} )\r\n) / sum by(node)( kube_node_status_allocatable {node=~\"$Node\", node=~\".*$NodeClass.*\", resource=\"ephemeral_storage\"} )",
       "legendFormat": "{{node}}: ephemeral_storage"
      }
     ]
    }
   ]
  },
  {
   "title": "Health: pods & containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Is Viya Up?",
     "type": "timeseries",
     "description": "Watch the sas-readiness container to see when viya begins starting up (container exists but ready=0), and viya startup complete (ready=1)\n",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (container,pod) (kube_pod_container_status_ready{namespace=~\"$namespace\", container=\"sas-readiness\"})",
       "legendFormat": "VIYA_UP({{container}})"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "timeseries",
     "description": "container restarts\n(Not a \"pod Terminated/restart\" count)",
     "gridPos": { "h": 9, "w": 6, "x": 5, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[1m])",
       "legendFormat": "restarts({{container}})"
      }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open File Descriptors per Pod -- (endpoint) > (sas_service_base) > (service) > (node)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 10, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "# ({{service}}) > ({{endpoint}}) > ({{sas_service_base}}) > ({{node}})\r\nprocess_open_fds{namespace=~\"$namespace\", pod=~\"$pod\", service!=\"\"}",
       "legendFormat": "({{service}}) > ({{endpoint}}) > ({{sas_service_base}}) > ({{node}})"
      },
      {
       "expr": "process_open_fds{namespace=~\"$namespace\", pod=~\"$pod\", service=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SAS Programming container count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count( container_start_time_seconds{node=~\"$Node\",namespace=~\"$namespace\",container=~\"sas-programming-environment\"} )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_requests (hits/second) by namespace",
     "type": "timeseries",
     "description": "http requests seen from the perspective of the nginx-ingress \"front door\". 1 minute moving window, so each data point shows the hits/second averaged over the past 1 minute.\n",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "#           sum by(exported_namespace) (    irate(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\", service=~\"$container\"}[1m]) ) \n#clamp_max( sum by(exported_namespace) ( increase(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\", service=~\"$container\"}[1m]) ), 10000 )\n            sum by(exported_namespace) (    irate(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\", service=~\"$container\"}[1m]) )",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    },
    {
     "title": "Pod Startup Time (wait+init+ready)",
     "type": "timeseries",
     "description": "time(podContainersReady) - time(podScheduled)\n\napproximate \"group by deployment|statefulset\" by using label_replace function and handling 3 different cases\n1. two random hash strings (or seq numbers) after 2nd to last dash\n2. one sequence number after last dash\n3. no random hash or sequence numbers\n\nif multiple pod replicas in a deployment or statefulset, display max value\n\n",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 27 },
     "targets": [
      {
       "expr": "# primary case: two random hashes after second to last dash at end of \"base app name\"\r\nmax by(podprefix) (\r\n    label_replace( kube_pod_status_ready_time    {namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"$container.*\", pod!~\"sas-readiness.*|sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+-[^-]+$\" )\r\n  - label_replace( kube_pod_status_scheduled_time{namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"$container.*\", pod!~\"sas-readiness.*|sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+-[^-]+$\" )\r\n)",
       "legendFormat": "{{podprefix}}"
      },
      {
       "expr": "# special case: only sequence number at end of \"base app name\"\r\nmax by(podprefix) (\r\n    label_replace( kube_pod_status_ready_time    {namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-default-worker.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+$\" )\r\n  - label_replace( kube_pod_status_scheduled_time{namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-default-worker.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+$\" )\r\n)\r\n",
       "legendFormat": "{{podprefix}}"
      },
      {
       "expr": "# special case: no random hashes or sequence numbers at end of \"base app name\"\r\nmax by(podprefix) (\r\n    label_replace( kube_pod_status_ready_time    {namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-cas-server-.*-controller\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)$\" )\r\n  - label_replace( kube_pod_status_scheduled_time{namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-cas-server-.*-controller\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)$\" )\r\n)",
       "legendFormat": "{{podprefix}}"
      }
     ]
    },
    {
     "title": "SAS Programming containers per node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by(node)( container_start_time_seconds{node=~\"$Node\",namespace=~\"$namespace\",container=\"sas-programming-environment\"} )\r\n"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_requests (hits/second) by service:endpoint",
     "type": "timeseries",
     "description": "http requests seen from the perspective of the nginx-ingress \"front door\". 1 minute moving window, so each data point shows the hits/second averaged over the past 1 minute.\n",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "#sum by (service,status) (    irate(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\", service=~\"$container\"}[1m]) )\n#sum by (service,path)   ( increase(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\", service=~\"$container\"}[1m]) )\n sum by (service,path)   (    irate(nginx_ingress_controller_requests{job=\"ingress-nginx\", exported_namespace=~\"$namespace\", service=~\"$container\"}[1m]) )\n",
       "legendFormat": "{{service}}:{{path}}"
      }
     ]
    },
    {
     "title": "Pod Startup Time (ready)",
     "type": "timeseries",
     "description": "time(podContainersReady) - time(podScheduled)\n\napproximate \"group by deployment|statefulset\" by using label_replace function and handling 3 different cases\n1. two random hash strings (or seq numbers) after 2nd to last dash\n2. one sequence number after last dash\n3. no random hash or sequence numbers\n\nif multiple pod replicas in a deployment or statefulset, display max value\n\n",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 36 },
     "targets": [
      {
       "expr": "# primary case: two random hashes after second to last dash at end of \"base app name\"\r\n  max by(podprefix) (label_replace( kube_pod_status_ready_time      {namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"$container.*\", pod!~\"sas-readiness.*|sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+-[^-]+$\" ) )\r\n- max by(podprefix) (label_replace( kube_pod_container_state_started{namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"$container.*\", pod!~\"sas-readiness.*|sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+-[^-]+$\" ) )",
       "legendFormat": "{{podprefix}}"
      },
      {
       "expr": "# special case: only sequence number at end of \"base app name\"\r\n  max by(podprefix) ( label_replace( kube_pod_status_ready_time      {namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-default-worker.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+$\" ) )\r\n- max by(podprefix) ( label_replace( kube_pod_container_state_started{namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-consul-server.*|sas-rabbitmq-server.*|sas-opendistro-default.*|sas-workload-orchestrator.*|sas-cas-server-default-worker.*\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)-[^-]+$\" ) )\r\n",
       "legendFormat": "{{podprefix}}"
      },
      {
       "expr": "# special case: no random hashes or sequence numbers at end of \"base app name\"\r\n  max by(podprefix) ( label_replace( kube_pod_status_ready_time      {namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-cas-server-.*-controller\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)$\" ) )\r\n- max by(podprefix) ( label_replace( kube_pod_container_state_started{namespace=~\"$namespace\", pod=~\"$pod\", pod=~\"sas-cas-server-.*-controller\"}, \"podprefix\", \"$1\", \"pod\", \"^(.+)$\" ) )",
       "legendFormat": "{{podprefix}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Autoscaling Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pod Replicas (by HPA)",
     "type": "timeseries",
     "description": "\"desired\" number of pod replicas from the perspective of the HorizontalPodAutoscaler",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "#sum by(hpa) (kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\"})\r\nsum by(horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\"})\r\n",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    },
    {
     "title": "Replicas (by Deployment)",
     "type": "timeseries",
     "description": "Number of pod replicas that have reached \"ContainersReady\" status (ie. containers in those pods have readiness probe \"ready=true\" and are ready to process HTTP requests).",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(deployment) (kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$pod\"})\r\n",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Autoscaling (Pods & Nodes)",
     "type": "timeseries",
     "description": "Pod replicas \"scheduled\" lags behind \"desired\" due to node startup time (this is normal).  \n",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(namespace) (kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\"})\r\n",
       "legendFormat": "HPA pod replicas desired ({{namespace}})"
      },
      {
       "expr": "sum by(namespace) (kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$pod\"\r\n  , deployment!=\"sas-opendistro-operator\"\r\n  , deployment!=\"sas-readiness\"\r\n  , deployment!=\"sas-prepull\"\r\n  , deployment!=\"sas-data-server-utility\"\r\n  , deployment!=\"sas-connect-spawner\"\r\n  , deployment!~\"sas-crunchy-data-postgres.*\"\r\n  , deployment!=\"sas-connect-spawner\"\r\n  , deployment!=\"sas-config-reconciler\"\r\n  , deployment!=\"sas-cas-operator\"\r\n  , deployment!=\"prometheus-pushgateway\"\r\n  , deployment!=\"sas-data-server-operator\"\r\n})",
       "legendFormat": "HPA pod replicas ready ({{namespace}})"
      },
      {
       "expr": "(sum by (label_agentpool) (kube_node_labels{node=~\"$Node\"}))\r\n",
       "legendFormat": "nodepool: {{label_agentpool}}"
      }
     ]
    }
   ]
  }
 ]
}