{
 "title": "Perf / Kubernetes Headroom",
 "tags": [
  "kubernetes-cluster",
  "welcome-cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Allocatable CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"memory\"})\r)"
    }
   ]
  },
  {
   "title": "Total Allocatable Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "Total Allocatable CPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"}) - sum(kube_pod_container_resource_requests_cpu_cores)\r"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"memory\"}) - sum(kube_pod_container_resource_requests_memory_bytes)\r)"
    }
   ]
  },
  {
   "title": "Total Allocatable Pods Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"}) - sum(kubelet_running_pods)"
    }
   ]
  },
  {
   "title": "% Allocatable CPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * (sum(kube_node_status_capacity{resource=\"cpu\"}) - sum(kube_pod_container_resource_requests_cpu_cores)) / sum(kube_node_status_capacity{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "% Allocatable Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(sum(kube_node_status_capacity{resource=\"memory\"}) - sum(kube_pod_container_resource_requests_memory_bytes)\r)/sum(kube_node_status_capacity{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "% Allocatable Pods Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * (sum(kube_node_status_capacity{resource=\"pods\"}) - sum(kubelet_running_pods)) / sum(kube_node_status_capacity{resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "Resources by Namespace",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)",
     "legendFormat": "cpu req"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)",
     "legendFormat": "mem req"
    },
    {
     "expr": "count(mixin_pod_workload) by (namespace)",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Resources by Node",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count by (node) (kube_pod_info)",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"}) by (node)",
     "legendFormat": "Pods Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)\r by (node)",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"}) by (node)",
     "legendFormat": "CPU Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (node)",
     "legendFormat": "Mem Requested"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) by (node)",
     "legendFormat": "Mem Allocatable"
    }
   ]
  }
 ]
}