{
 "title": "SingleStore: Detailed Cluster View By Node",
 "tags": [
  "singlestore",
  "sas-speedystore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select distinct(cluster) from metrics where $__unixEpochFilter(time_sec)"
   },
   {
    "name": "database_name",
    "query": "select distinct(database_name) from act_samples where $__timeFilter(ts) and (cluster = '$cluster')"
   },
   {
    "name": "host",
    "query": "select distinct(host) from metrics where host is not NULL and $__unixEpochFilter(time_sec) and (cluster='$cluster')"
   },
   {
    "name": "port",
    "query": "select distinct(port) from metrics where host is not NULL and $__unixEpochFilter(time_sec) and (cluster='$cluster') and (host in ($host) or concat($host) = '%') and port is not null"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization per Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH t1 AS (WITH t AS (\n    SELECT *, lag(value) OVER w value_l, lag(time_sec) OVER w time_sec_l\n    FROM\n        (SELECT\n-- take the last datapoint in the interval\ntime_sec as time_sec,\nmemsql_sysinfo_cpu_used_ms/memsql_sysinfo_cpu_num_cpus value,\nhost\n         FROM\n             (SELECT\n             max(time_sec) time_sec,\n             -- this is the last counter in the time group\n             max(intval) as value,\n             name as metric,\n             trim_host(host) host,\n             $__unixEpochGroup(time_sec, $interval) as tg\n             FROM metrics\n             WHERE\n             (cluster = '$cluster')\n             and (host in ($host) or concat($host) = '%')\n             and (extractor = 'memsql')\n             and (subsystem = 'sysinfo')\n             and (name = 'memsql_sysinfo_cpu_used_ms' or name = 'memsql_sysinfo_cpu_num_cpus')\n             and $__unixEpochFilter(time_sec)\n             group by metric, host, tg\n             ) as pvt_data\n             PIVOT\n             (\n                AVG(value)\n                FOR metric\n                IN ('memsql_sysinfo_cpu_used_ms', 'memsql_sysinfo_cpu_num_cpus')\n             ) as pvt_table\n        ) X\n        WINDOW w AS (partition by host order by time_sec desc)\n)\nselect a.time_sec, (value - value_l)/(1000*(time_sec - time_sec_l)) * 100 value, a.host from t a\nWHERE time_sec_l is not null and value_l is not null\norder by 1, 2 desc, 3)\nSELECT time_sec, host, max(value) 'CPU:' from t1\ngroup by time_sec, host\norder by time_sec, host\n"
    }
   ]
  },
  {
   "title": "Memory Utilization per Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select * from (\nselect time_sec,\nhost,\nmemsql_sysinfo_mem_used_b / memsql_sysinfo_mem_total_b as 'Memory:'\nFROM\n(SELECT\n  max(time_sec) time_sec,\n  avg(value) value,\n  metric,\n  host\n  FROM\n  (SELECT\n    time_sec,\n    $__unixEpochGroup(time_sec,$interval) tg,\n    intval as value,\n    name as metric,\n    trim_host(host) as host\n    FROM metrics\n    WHERE cluster='$cluster'\n    and (host in ($host) or concat($host) = '%')\n    and extractor = 'memsql'\n    and subsystem = 'sysinfo'\n    and name in ('memsql_sysinfo_mem_used_b','memsql_sysinfo_mem_total_b')\n    and $__unixEpochFilter(time_sec)\n  ) X\n  GROUP BY tg, metric, host\n) as pvt_data\nPIVOT (\n        AVG(value) \n        FOR metric \n        IN ('memsql_sysinfo_mem_used_b','memsql_sysinfo_mem_total_b')\n) as pvt_table) a\norder by time_sec"
    }
   ]
  },
  {
   "title": "Disk Utilization per Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select * from (\nselect time_sec,\nhost,\nmemsql_sysinfo_disk_used_b / memsql_sysinfo_disk_total_b as 'Disk:'\nFROM\n(SELECT\n  max(time_sec) time_sec,\n  avg(value) value,\n  metric,\n  host\n  FROM\n  (SELECT\n    time_sec,\n    $__unixEpochGroup(time_sec,$interval) tg,\n    intval as value,\n    name as metric,\n    trim_host(host) as host\n    FROM metrics\n    WHERE cluster='$cluster'\n    and (host in ($host) or concat($host) = '%')\n    and extractor = 'memsql'\n    and subsystem = 'sysinfo'\n    and name in ('memsql_sysinfo_disk_used_b','memsql_sysinfo_disk_total_b')\n    and $__unixEpochFilter(time_sec)\n  ) X\n  GROUP BY tg, metric, host\n) as pvt_data\nPIVOT (\n        AVG(value) \n        FOR metric \n        IN ('memsql_sysinfo_disk_used_b','memsql_sysinfo_disk_total_b')\n) as pvt_table) a\norder by time_sec"
    }
   ]
  },
  { "title": "Connections & Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Threads - Connected",
   "type": "timeseries",
   "description": "Number of open connections (threads_connected) to the database relative to the maximum limit (max_connections). If the utilization is near 100%, it means DB is approaching the maximum allowed connections; this can potentially lead to performance issues, as queries may need to wait in a queue until a thread becomes available to process them.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select tg as time,\n       concat(host,':',port,' {',role,'}') as node,\n        max(used_c / total_C) * 100 as 'Threads - Connected:'\nfrom (SELECT time_sec as time, \n             $__unixEpochGroup(time_sec, $interval) as tg, \n             sum(case when name = 'memsql_variables_max_connections' then value else 0 end) as total_c,\n             sum(case when name = 'memsql_status_threads_connected' then value else 0 end) as used_c,\n             host, port, role\n     FROM metrics\n     WHERE $__unixEpochFilter(time_sec) AND\n           (cluster = '$cluster') AND\n           (host in ($host) or concat($host) = '%') AND\n           (port in ($port) or concat($port) = '%') AND\n           NAME in ('memsql_variables_max_connections','memsql_status_threads_connected') \n     group by time, tg, host, port, role)\ngroup by tg, node\norder by tg, node;"
    }
   ]
  },
  {
   "title": "Threads - Running",
   "type": "timeseries",
   "description": "Number of threads actively running queries (threads_running) relative to the maximum limit (max_connection_threads). If the utilization is near 100%, it suggests that the system might be reaching its capacity in terms of how many queries can be executed in parallel. This situation can lead to resource pressure, unresponsiveness, latency spikes, and even failures",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select tg as time,\n       concat(host,':',port,' {',role,'}') as node,\n       max(used_c / total_C) * 100 as 'Threads - Running:' \nfrom (SELECT time_sec as time, \n             $__unixEpochGroup(time_sec, $interval) as tg, \n             sum(case when name = 'memsql_variables_max_connection_threads' then value else 0 end) as total_c,\n             sum(case when name = 'memsql_status_threads_running' then value else 0 end) as used_c,\n             host, port, role\n     FROM metrics\n     WHERE $__unixEpochFilter(time_sec) AND\n           (cluster = '$cluster') AND\n           (host in ($host) or concat($host) = '%') AND\n           (port in ($port) or concat($port) = '%') AND\n           NAME in ('memsql_variables_max_connection_threads','memsql_status_threads_running') \n     group by time, tg, host, port, role)\ngroup by tg, node\norder by tg, node;"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Write Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n  SELECT \n    *, \n    lag(value) OVER w value_l, \n    lag(time_sec) OVER w time_sec_l \n  FROM \n    (\n      SELECT \n        max(time_sec) as time_sec, \n        avg(value) as value, \n        host , port, name, role\n      FROM \n        (\n          SELECT \n            time_sec, \n            $__unixEpochGroup(time_sec, $interval) as tg, \n            intval as value, \n            host , port, name, role\n          FROM \n            `metrics` \n          WHERE \n            $__unixEpochFilter(time_sec) \n            and (cluster = '$cluster') \n            and (host in ($host) or concat($host) = '%')\n            and (port in ($port) or concat($port) = '%')\n            and extractor = 'memsql' \n            and subsystem = 'status' \n            and name like 'memsql_status_%_write_queries'\n            and role <> 'LEAF') subq \n      GROUP BY \n        host, port, name, role,\n        tg\n    ) X WINDOW w AS (\n      partition by host, port , name\n      order by \n        time_sec\n    )\n) \nSELECT \n  time_sec, \n  concat(host,':',port,' {',role,'}') as node,\n  sum((value - value_l)/(time_sec - time_sec_l)) as 'Write queries per second:'\nFROM \n  t a \nwhere \n  time_sec_l is not null \n  and value_l is not null \n and value >= value_l \ngroup by\n  1,2\norder by \n  1,2"
    }
   ]
  },
  {
   "title": "Rows Written per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n  SELECT \n    *, \n    lag(value) OVER w value_l, \n    lag(time_sec) OVER w time_sec_l \n  FROM \n    (\n      SELECT \n        max(time_sec) as time_sec, \n        max(value) as value, \n        host, port, role\n      FROM \n        (\n          SELECT \n            time_sec, \n            $__unixEpochGroup(time_sec, $interval) as tg, \n            intval as value, \n            host, port , role\n          FROM \n            `metrics` \n          WHERE \n            $__unixEpochFilter(time_sec) \n            and (cluster = '$cluster') \n            and (host in ($host) or concat($host) = '%')\n            and (port in ($port) or concat($port) = '%')\n            and extractor = 'memsql' \n            and subsystem = 'status' \n            and name = 'memsql_status_rows_affected_by_writes'\n            and role <> 'LEAF') subq \n      GROUP BY \n        host, port, role,\n        tg\n    ) X WINDOW w AS (\n      partition by host, port \n      order by \n        time_sec\n    )\n) \nSELECT \n  time_sec, \n  concat(host,':',port,' {',role,'}') as node,\n  sum((value - value_l)/(time_sec - time_sec_l)) as 'Rows written per second:'\nFROM \n  t a \nwhere \n  time_sec_l is not null \n  and value_l is not null \n and value >= value_l \ngroup by 1,2\norder by \n  1,2"
    }
   ]
  },
  {
   "title": "Failed Write Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n  SELECT \n    *, \n    lag(value) OVER w value_l, \n    lag(time_sec) OVER w time_sec_l \n  FROM \n    (\n      SELECT \n        max(time_sec) as time_sec, \n        avg(value) as value, \n        host , port, role\n      FROM \n        (\n          SELECT \n            time_sec, \n            $__unixEpochGroup(time_sec, $interval) as tg, \n            intval as value, \n            host , port, role\n          FROM \n            `metrics` \n          WHERE \n            $__unixEpochFilter(time_sec) \n            and (cluster = '$cluster') \n            and (host in ($host) or concat($host) = '%')\n            and (port in ($port) or concat($port) = '%')\n            and extractor = 'memsql' \n            and subsystem = 'status' \n            and name like 'memsql_status_failed_write_queries'\n            and role <> 'LEAF') subq \n      GROUP BY \n        host, port, role,\n        tg\n    ) X WINDOW w AS (\n      partition by host, port \n      order by \n        time_sec\n    )\n) \nSELECT \n  time_sec, \n  concat(host,':',port,' {',role,'}') as node,\n  sum((value - value_l)/(time_sec - time_sec_l)) as 'Failed Write queries per second:'\nFROM \n  t a \nwhere \n  time_sec_l is not null \n  and value_l is not null \n and value >= value_l \ngroup by\n  1,2\norder by \n  1,2"
    }
   ]
  },
  {
   "title": "Execution Time per Write Query",
   "type": "timeseries",
   "description": "Changes in the pattern of execution time per write query from the historical norm may indicate an issue with your application or changes in your workload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n            SELECT \n                *, \n                lag(value) OVER w value_l, \n                lag(time) OVER w time_l\n            from (\n                  select max(tg) as time,\n                         max(value) as value,\n                         host,port, name, role\n                  from (\n                        SELECT  time_sec,\n                                $__unixEpochGroup(time_sec, $interval) as tg, \n                                host,\n                                port,role,\n                                name,\n                                value\n                        FROM metrics\n                        WHERE $__unixEpochFilter(time_sec) AND\n                              cluster = '$cluster' AND\n                              (host in ($host) or concat($host) = '%') AND\n                              (port in ($port) or concat($port) = '%') AND\n                              role <> 'LEAF' AND\n                              name in ('memsql_status_failed_write_queries','memsql_status_successful_write_queries','memsql_status_execution_time_of_write')\n                        )\n                  group by name, host, port, role, tg) X \n            WINDOW w AS (partition by host,port,name order by time))\nselect time, \n       concat(host,':',port,' {',role,'}') as node,\n       sum(case when name = 'memsql_status_execution_time_of_write' then (value - value_l) end) /\n       sum(case when name in ('memsql_status_failed_write_queries','memsql_status_successful_write_queries') then (value - value_l) end) as 'Execution Time per Write Query:'\nfrom t\nwhere time_l is not null \n  and value_l is not null \n  and value >= value_l\ngroup by time, node\norder by time, node"
    }
   ]
  },
  {
   "title": "Read Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n  SELECT \n    *, \n    lag(value) OVER w value_l, \n    lag(time_sec) OVER w time_sec_l \n  FROM \n    (\n      SELECT \n        max(time_sec) as time_sec, \n        avg(value) as value, \n        host , port, name, role\n      FROM \n        (\n          SELECT \n            time_sec, \n            $__unixEpochGroup(time_sec, $interval) as tg, \n            intval as value, \n            host , port, name, role\n          FROM \n            `metrics` \n          WHERE \n            $__unixEpochFilter(time_sec) \n            and (cluster = '$cluster') \n            and (host in ($host) or concat($host) = '%')\n            and (port in ($port) or concat($port) = '%')\n            and extractor = 'memsql' \n            and subsystem = 'status' \n            and name like 'memsql_status_%_read_queries'\n            and role <> 'LEAF') subq \n      GROUP BY \n        host, port, name, role,\n        tg\n    ) X WINDOW w AS (\n      partition by host, port , name\n      order by \n        time_sec\n    )\n) \nSELECT \n  time_sec, concat(host,':',port,' {',role,'}') as node,\n  sum((value - value_l)/(time_sec - time_sec_l)) as 'Read queries per second:'\nFROM \n  t a \nwhere \n  time_sec_l is not null \n  and value_l is not null \n and value >= value_l \ngroup by\n  1,2\norder by \n  1,2"
    }
   ]
  },
  {
   "title": "Rows Read per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n    SELECT\n        *,\n        lag(value) OVER w value_l,\n            lag(time_sec) OVER w time_sec_l\n    FROM\n        (\n            SELECT\n                max(time_sec) as time_sec,\n                max(value) as value, \n        host, port, role\n            FROM\n                (\n                SELECT\n                time_sec,\n                $__unixEpochGroup(time_sec, $interval) as tg,\n                intval as value,\n                host, port, role\n                FROM\n                `metrics`\n                WHERE\n                $__unixEpochFilter(time_sec)\n                and (cluster = '$cluster')\n                and (host in ($host) or concat($host) = '%')\n                and (port in ($port) or concat($port) = '%')\n                and extractor = 'memsql'\n                and subsystem = 'status'\n                and name = 'memsql_status_rows_returned_by_reads'\n                and role <> 'LEAF') subq\n            GROUP BY\n                host, port, role,\n                tg\n        ) X WINDOW w AS (\n        partition by host, port\n        order by\n            time_sec\n        )\n)\nSELECT\n    time_sec,\n    concat(host,':',port,' {',role,'}') as node,\n    sum((value - value_l)/(time_sec - time_sec_l)) as 'Rows Read per second:'\nFROM\n    t a\nwhere\n    time_sec_l is not null\n  and value_l is not null\n  and value >= value_l\ngroup by 1,2\norder by\n    1,2"
    }
   ]
  },
  {
   "title": "Failed Read Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n  SELECT \n    *, \n    lag(value) OVER w value_l, \n    lag(time_sec) OVER w time_sec_l \n  FROM \n    (\n      SELECT \n        max(time_sec) as time_sec, \n        avg(value) as value, \n        host , port, role\n      FROM \n        (\n          SELECT \n            time_sec, \n            $__unixEpochGroup(time_sec, $interval) as tg, \n            intval as value, \n            host , port, role\n          FROM \n            `metrics` \n          WHERE \n            $__unixEpochFilter(time_sec) \n            and (cluster = '$cluster') \n            and (host in ($host) or concat($host) = '%')\n            and (port in ($port) or concat($port) = '%')\n            and extractor = 'memsql' \n            and subsystem = 'status' \n            and name like 'memsql_status_failed_read_queries'\n            and role <> 'LEAF') subq \n      GROUP BY \n        host, port, role,\n        tg\n    ) X WINDOW w AS (\n      partition by host, port \n      order by \n        time_sec\n    )\n) \nSELECT \n  time_sec, concat(host,':',port,' {',role,'}') as node,\n  sum((value - value_l)/(time_sec - time_sec_l)) as 'Failed Read queries per second:'\nFROM \n  t a \nwhere \n  time_sec_l is not null \n  and value_l is not null \n and value >= value_l \ngroup by\n  1,2\norder by \n  1,2"
    }
   ]
  },
  {
   "title": "Execution Time per Read Query",
   "type": "timeseries",
   "description": "Changes in the pattern of execution time per read query from the historical norm may indicate an issue with your application or changes in your workload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n            SELECT \n                *, \n                lag(value) OVER w value_l, \n                lag(time) OVER w time_l\n            from (\n                  select max(tg) as time,\n                         max(value) as value,\n                         host,port, name, role\n                  from (\n                        SELECT  time_sec,\n                                $__unixEpochGroup(time_sec, $interval) as tg, \n                                host,\n                                port, role,\n                                name,\n                                value\n                        FROM metrics\n                        WHERE $__unixEpochFilter(time_sec) AND\n                              cluster = '$cluster' AND\n                              (host in ($host) or concat($host) = '%') AND\n                              (port in ($port) or concat($port) = '%') AND\n                              role <> 'LEAF' AND\n                              name in ('memsql_status_failed_read_queries','memsql_status_successful_read_queries','memsql_status_execution_time_of_reads')\n                        )\n                  group by name, host, port,role, tg) X \n            WINDOW w AS (partition by host,port,name order by time))\nselect time, \n       concat(host,':',port,' {',role,'}') as node,\n       sum(case when name = 'memsql_status_execution_time_of_reads' then (value - value_l) end) /\n       sum(case when name in ('memsql_status_failed_read_queries','memsql_status_successful_read_queries') then (value - value_l) end) as 'Execution Time per read Query:'\nfrom t\nwhere time_l is not null \n  and value_l is not null \n  and value >= value_l\ngroup by time, node\norder by time, node"
    }
   ]
  },
  {
   "title": "Network Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\nSELECT *, lag(value) OVER w value_l, lag(time_sec) OVER w time_sec_l\nFROM \n(SELECT\n  max(time_sec) time_sec,\n  $__unixEpochGroup(time_sec,$interval) tg,\n  avg(intval) as value,\n  trim_metric(name, 'memsql_status_bytes_') as metric,\n  trim_host(host) host,\n  port, role\nFROM metrics\nWHERE (cluster = '$cluster')\nand (extractor = 'memsql')\nand (subsystem = 'status')\nand name in ('memsql_status_bytes_received')\nand (host in ($host) or concat($host) = '%')\nand (port in ($port) or concat($port) = '%')\nand $__unixEpochFilter(time_sec)\nGROUP BY metric, host, port, role, tg\n) X\nWINDOW w AS (partition by metric, host, port order by time_sec desc)\n)\nselect time_sec, concat(host,':',port,' {',role,'}') as node, sum((value - value_l)/(time_sec - time_sec_l)) 'Network Received bytes:'\nfrom t a\nwhere time_sec_l is not null and value_l is not null\ngroup by 1,2\norder by 1,2"
    }
   ]
  },
  {
   "title": "Network Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\nSELECT *, lag(value) OVER w value_l, lag(time_sec) OVER w time_sec_l\nFROM \n(SELECT\n  max(time_sec) time_sec,\n  $__unixEpochGroup(time_sec,$interval) tg,\n  avg(intval) as value,\n  trim_metric(name, 'memsql_status_bytes_') as metric,\n  trim_host(host) host,\n  port, role\nFROM metrics\nWHERE (cluster = '$cluster')\nand (extractor = 'memsql')\nand (subsystem = 'status')\nand name in ('memsql_status_bytes_sent')\nand (host in ($host) or concat($host) = '%')\nand (port in ($port) or concat($port) = '%')\nand $__unixEpochFilter(time_sec)\nGROUP BY metric, host, port, role, tg\n) X\nWINDOW w AS (partition by metric, host, port order by time_sec desc)\n)\nselect time_sec, concat(host,':',port,' {',role,'}') as node, sum((value - value_l)/(time_sec - time_sec_l)) 'Network Sent bytes:' \nfrom t a\nwhere time_sec_l is not null and value_l is not null\ngroup by 1,2\norder by 1,2"
    }
   ]
  }
 ]
}