{
 "title": "SingleStore: Historical Workload Monitoring",
 "tags": [
  "singlestore",
  "sas-speedystore"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "viewName", "query": "0cda4387b1a7" },
   {
    "name": "cluster",
    "query": "select distinct(cluster) from `act_samples` where $__timeFilter(ts)"
   },
   {
    "name": "database_name",
    "query": "select distinct(ifnull(database_name,'-')) from `act_samples` where (cluster = '$cluster') and $__timeFilter(ts)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d" },
   {
    "name": "hidden_activity_name",
    "label": "Query Plan ID",
    "query": "All, Select a query in the table below"
   },
   {
    "name": "query_plan_hidden",
    "label": "Query Plan",
    "query": "All, Select a query in the table below"
   },
   {
    "name": "activity_name",
    "query": "select case when '$hidden_activity_name' = 'All' then 'All' else query_text end \nfrom `mv_queries`  \nwhere  (cluster = '$cluster') and \nactivity_name in ('$hidden_activity_name')"
   },
   { "name": "topn", "label": "Top N (Query Plan)", "query": "100,250,500,1000" },
   {
    "name": "sortby",
    "label": "Sort By",
    "query": "Avg. Elapsed Time,Total Elapsed Time,Avg. CPU Time,Total CPU Time,Avg. Memory Bytes, Avg. Disk Bytes, Avg. Disk Read Bytes (logical), Avg. Disk Write Bytes (logical), Avg. Network Bytes,Avg. Network Received Bytes (logical), Avg. Network Send Bytes (logical), Execution Count,Failure Count,Failure Rate"
   }
  ]
 },
 "panels": [
  {
   "title": "Elapsed Time per Execution by Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\nSELECT  *,\n        lag(ts) OVER w ts_l,\n        lag(total) OVER w total_l,\n        lag(elp) OVER w elp_l\nFROM (\n        select  ts,\n                cluster,\n                activity_name name,\n                ifnull(aggregator_activity_name, activity_name) agg_name,\n                database_name db,\n                sum(elapsed_time_ms) as elp,\n                sum(IFNULL(memory_major_faults,0)+IFNULL(success_count,0)+IFNULL(failure_count,0)) total\n        from `act_samples` act\n        where $__timeFilter(ts)\n        and (cluster = '$cluster')\n        and (database_name in ($database_name) or '%' in ($database_name) or ('-' in ($database_name) and database_name is null))\n        and (activity_type = 'Query')\n        and ('All' in ('$hidden_activity_name') OR 'Select a query in the table below' in ('$hidden_activity_name') OR activity_name = '$hidden_activity_name')\n        and activity_name = agg_name\n        group by 1,2,3,4,5\n      ) q\nWINDOW w AS(partition by cluster, db, name order by ts) )\nselect $__timeGroup(ts,$interval) time_sec,\n       a.db,\n       sum(a.elp - a.elp_l)/sum(a.total- a.total_l) ' '\nfrom t a\nwhere a.total >a.total_l and\n      a.elp >a.elp_l\ngroup by 1,2\norder by 1"
    }
   ]
  },
  {
   "title": "Execution Count",
   "type": "timeseries",
   "description": "Number of query executions",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\nSELECT  *,\n        lag(ts) OVER w ts_l,\n        lag(total) OVER w total_l\nFROM (\n        select  ts,\n                cluster,\n                activity_name name,\n                ifnull(aggregator_activity_name, activity_name) agg_name,\n                database_name db,\n                sum(IFNULL(memory_major_faults,0)+IFNULL(success_count,0)+IFNULL(failure_count,0)) total\n        from `act_samples` act\n        where $__timeFilter(ts)\n        and (cluster = '$cluster')\n        and (database_name in ($database_name) or '%' in ($database_name) or ('-' in ($database_name) and database_name is null))\n        and (activity_type = 'Query')\n        and ('All' in ('$hidden_activity_name') OR 'Select a query in the table below' in ('$hidden_activity_name') OR activity_name = '$hidden_activity_name')\n        and activity_name = agg_name\n        group by 1,2,3,4,5\n      ) q\nWINDOW w AS(partition by cluster, db, name order by ts))\nselect $__timeGroup(ts,$interval) time_sec,\n       sum(a.total- a.total_l) execution_count\nfrom t a\nwhere a.total>a.total_l\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time per Execution by Database",
     "type": "timeseries",
     "description": "Time spent running on all the CPUs across the workspace reported by database",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "WITH t AS (\nSELECT  *,\n        lag(ts) OVER w ts_l,\n        lag(total) OVER w total_l,\n        lag(cpu) OVER w cpu_l\nFROM (\n        select  ts,\n                cluster,\n                ifnull(act.aggregator_activity_name, act.activity_name) name,\n                database_name db,\n                sum(cpu_time_ms) as cpu,\n                sum(if(activity_name = name, IFNULL(memory_major_faults,0), 0) +\n                    if(activity_name = name, IFNULL(success_count,0), 0) +\n                    if(activity_name = name, IFNULL(failure_count,0), 0)) total\n        from `act_samples` act\n        where $__timeFilter(ts)\n        and (cluster = '$cluster')\n        and (database_name in ($database_name) or '%' in ($database_name) or ('-' in ($database_name) and database_name is null))\n        and (activity_type = 'Query')\n        and ('All' in ('$hidden_activity_name') OR 'Select a query in the table below' in ('$hidden_activity_name') OR name = '$hidden_activity_name')\n        group by 1,2,3,4\n      ) q\nWINDOW w AS(partition by cluster, db, name order by ts) )\nselect $__timeGroup(ts,$interval) time_sec,\n       a.db,\n       sum(a.cpu - a.cpu_l)/sum(a.total- a.total_l) ' '\nfrom t a\nwhere a.total > 0 and\n      a.total >a.total_l and\n      a.cpu >a.cpu_l\ngroup by 1,2\norder by 1"
      }
     ]
    },
    {
     "title": "Memory Bytes per Execution by Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "WITH t AS (\nSELECT  *,\n        lag(ts) OVER w ts_l,\n        lag(elp) OVER w elp_l,\n        lag(memory_bs) OVER w memory_bs_l\nFROM (\n        select  ts,\n                cluster,\n                ifnull(act.aggregator_activity_name, act.activity_name) name,\n                database_name db,\n                sum(if(activity_name = name, elapsed_time_ms,0)) as elp,\n                sum(memory_bs) as memory_bs\n        from `act_samples` act\n        where $__timeFilter(ts)\n        and (cluster = '$cluster')\n        and (database_name in ($database_name) or '%' in ($database_name) or ('-' in ($database_name) and database_name is null))\n        and (activity_type = 'Query')\n        and ('All' in ('$hidden_activity_name') OR 'Select a query in the table below' in ('$hidden_activity_name') OR name = '$hidden_activity_name')\n        group by 1,2,3,4\n      ) q\nWINDOW w AS(partition by cluster, db, name order by ts) )\nselect $__timeGroup(ts,$interval) time_sec,\n       a.db,\n       sum(1000*(a.memory_bs - a.memory_bs_l))/sum(a.elp- a.elp_l) ' '\nfrom t a\nwhere a.elp > 0 and\n      a.memory_bs >a.memory_bs_l and\n      a.elp >a.elp_l\ngroup by 1,2\norder by 1"
      }
     ]
    },
    {
     "title": "Disk Bytes per Execution by Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "WITH t AS (\nSELECT  *,\n        lag(ts) OVER w ts_l,\n        lag(total) OVER w total_l,\n        lag(disk_b) OVER w disk_b_l\nFROM (\n        select  ts,\n                cluster,\n                ifnull(act.aggregator_activity_name, act.activity_name) name,\n                database_name db,\n                sum(disk_b) as disk_b,\n                sum(if(activity_name = name, IFNULL(memory_major_faults,0), 0) +\n                    if(activity_name = name, IFNULL(success_count,0), 0) +\n                    if(activity_name = name, IFNULL(failure_count,0), 0)) total\n        from `act_samples` act\n        where $__timeFilter(ts)\n        and (cluster = '$cluster')\n        and (database_name in ($database_name) or '%' in ($database_name) or ('-' in ($database_name) and database_name is null))\n        and (activity_type = 'Query')\n        and ('All' in ('$hidden_activity_name') OR 'Select a query in the table below' in ('$hidden_activity_name') OR name = '$hidden_activity_name')\n        group by 1,2,3,4\n      ) q\nWINDOW w AS(partition by cluster, db, name order by ts) )\nselect $__timeGroup(ts,$interval) time_sec,\n       a.db,\n       sum(a.disk_b - a.disk_b_l)/sum(a.total- a.total_l) ' '\nfrom t a\nwhere a.total > 0 and\n      a.total >a.total_l and\n      a.disk_b >a.disk_b_l\ngroup by 1,2\norder by 1"
      }
     ]
    },
    {
     "title": "Network Bytes per Execution by Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "WITH t AS (\nSELECT  *,\n        lag(ts) OVER w ts_l,\n        lag(total) OVER w total_l,\n        lag(network_b) OVER w network_b_l\nFROM (\n        select  ts,\n                cluster,\n                ifnull(act.aggregator_activity_name, act.activity_name) name,\n                database_name db,\n                sum(network_b) as network_b,\n                sum(if(activity_name = name, IFNULL(memory_major_faults,0), 0) +\n                    if(activity_name = name, IFNULL(success_count,0), 0) +\n                    if(activity_name = name, IFNULL(failure_count,0), 0)) total\n        from `act_samples` act\n        where $__timeFilter(ts)\n        and (cluster = '$cluster')\n        and (database_name in ($database_name) or '%' in ($database_name) or ('-' in ($database_name) and database_name is null))\n        and (activity_type = 'Query')\n        and ('All' in ('$hidden_activity_name') OR 'Select a query in the table below' in ('$hidden_activity_name') OR name = '$hidden_activity_name')\n        group by 1,2,3,4\n      ) q\nWINDOW w AS(partition by cluster, db, name order by ts) )\nselect $__timeGroup(ts,$interval) time_sec,\n       a.db,\n       sum(a.network_b - a.network_b_l)/sum(a.total- a.total_l) ' '\nfrom t a\nwhere a.total > 0 and\n      a.total >a.total_l and\n      a.network_b >a.network_b_l\ngroup by 1,2\norder by 1"
      }
     ]
    }
   ]
  },
  { "title": "Metrics by Query Plan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Metrics by Query Plan",
   "type": "table",
   "description": "Elapsed Time - Wall clock milliseconds elapsed during execution;                          CPU Time - Milliseconds spent running on all the CPUs across the workspace. This is likely to exceed the observed elapsed time because the tasks are likely to have executed concurrently",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select res.*, q.query_text as query_plan from ( \nWITH t AS (\n\nSELECT *,\nlag(cpu) OVER w cpu_l,\nlag(disk_b) OVER w disk_b_l,\nlag(disk_logical_read_b) OVER w disk_logical_read_b_l,\nlag(disk_logical_write_b) OVER w disk_logical_write_b_l,\nlag(network_b) OVER w network_b_l,\nlag(network_logical_recv_b) OVER w network_logical_recv_b_l,\nlag(network_logical_send_b) OVER w network_logical_send_b_l,\nlag(memory_bs) OVER w memory_bs_l,\nlag(elp) OVER w elp_l,\nlag(fail) OVER w fail_l,\nlag(total) OVER w total_l\nFROM\n(\nselect\nact.cluster,\nact.ts,\nifnull(database_name,'-') db,\nifnull(act.aggregator_activity_name, act.activity_name) uniq_act,\nsum(cpu_time_ms) cpu,\nsum(disk_b) disk_b,\nsum(disk_logical_read_b) disk_logical_read_b,\nsum(disk_logical_write_b) disk_logical_write_b,\nsum(network_b) network_b,\nsum(network_logical_recv_b) network_logical_recv_b,\nsum(network_logical_send_b) network_logical_send_b,\nsum(memory_bs) memory_bs,\nsum(if (activity_name = uniq_act, elapsed_time_ms, 0)) elp,\nsum(if(activity_name = uniq_act, IFNULL(failure_count,0), 0)) fail,\nsum(if(activity_name = uniq_act, IFNULL(memory_major_faults,0), 0) +\n    if(activity_name = uniq_act, IFNULL(success_count,0), 0) +\n    if(activity_name = uniq_act, IFNULL(failure_count,0), 0)) total\nfrom `act_samples` act\nwhere $__timeFilter(act.ts)\nand (cluster = '$cluster')\nand (database_name in ($database_name) or '%' in ($database_name) or ('-' in ($database_name) and database_name is null))\nand ('All' in ('$hidden_activity_name') OR 'Select a query in the table below' in ('$hidden_activity_name') \n    OR (uniq_act in ('$hidden_activity_name'))\n    )\nand (act.activity_type = 'Query')\ngroup by 1,2,3,4\n) q\nWINDOW w AS(partition by cluster, db, uniq_act order by ts) \n)\nselect \ndb, \nelp as 'Total Elapsed Time', \nelp/total 'Avg. Elapsed Time', \ncpu as 'Total CPU Time', \ncpu/total as 'Avg. CPU Time',\ndisk_b/total as 'Avg. Disk Bytes',\ndisk_logical_read_b/total as 'Avg. Disk Read Bytes (logical)',\ndisk_logical_write_b/total as 'Avg. Disk Write Bytes (logical)',\nnetwork_logical_recv_b/total as 'Avg. Network Received Bytes (logical)',\nnetwork_logical_send_b/total as 'Avg. Network Send Bytes (logical)',\nnetwork_b/total as 'Avg. Network Bytes',\n(1000*memory_bs)/elp as 'Avg. Memory Bytes',\ntotal as 'Execution Count', \nfail as 'Failure Count',\nfail/total as 'Failure Rate', \nuniq_act\nFROM (select \na.cluster, a.db,\nsum(if(a.cpu>a.cpu_l, a.cpu- a.cpu_l,0)) cpu, \nsum(if(a.disk_b>a.disk_b_l, a.disk_b- a.disk_b_l,0)) disk_b, \nsum(if(a.disk_logical_read_b>a.disk_logical_read_b_l, a.disk_logical_read_b- a.disk_logical_read_b_l,0)) disk_logical_read_b, \nsum(if(a.disk_logical_write_b>a.disk_logical_write_b_l, a.disk_logical_write_b- a.disk_logical_write_b_l,0)) disk_logical_write_b, \nsum(if(a.network_b>a.network_b_l, a.network_b- a.network_b_l,0)) network_b, \nsum(if(a.network_logical_recv_b>a.network_logical_recv_b_l, a.network_logical_recv_b- a.network_logical_recv_b_l,0)) network_logical_recv_b, \nsum(if(a.network_logical_send_b>a.network_logical_send_b_l, a.network_logical_send_b- a.network_logical_send_b_l,0)) network_logical_send_b,\nsum(if(a.memory_bs>a.memory_bs_l, a.memory_bs- a.memory_bs_l,0)) memory_bs,\nsum(if(a.elp>a.elp_l, a.elp- a.elp_l,0)) elp, \nsum(if(a.fail>a.fail_l, a.fail- a.fail_l,0)) fail, \nsum(if(a.total>a.total_l, a.total- a.total_l,0)) total,\na.uniq_act\nfrom t a\nwhere total > 0 and elp > 0\ngroup by uniq_act) subq\nWHERE (subq.total > 0)\n) res,  `mv_queries` q\nwhere res.uniq_act = q.activity_name\norder by `$sortby` desc\nlimit $topn"
    }
   ]
  },
  {
   "title": "select a query in the table above to view its text",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "content": "${activity_name}" }
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": {
    "content": "**Elapsed Time** - Wall clock milliseconds elapsed during execution    \n\n**CPU Time** - The units of CPU Time are 'core ms' because it's the time spent running on each CPU core across the workspace.  This is likely to exceed the observed elapsed time because the tasks are likely to have executed concurrently\n\n**query_plan** - Query plans are compiled to machine code from the query by parameterizing the values and cached to expedite subsequent executions.<br />\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For Instance: Let's say you execute the below 2 queries,<br />\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Select * from table_a where colum_a = \"Value_A\"<br />\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Select * from table_a where column_a = \"Value_B\"<br />\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Query Plan for the above two queries would look something like the below,<br />\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Select * from table_a where column_a = ^<br />"
   }
  }
 ]
}