{
 "title": "SingleStore: Memory Usage",
 "tags": [
  "singlestore",
  "sas-speedystore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select distinct(cluster) from metrics where $__unixEpochFilter(time_sec)"
   },
   {
    "name": "host",
    "query": "select distinct(host) from metrics where cluster = '$cluster' and $__unixEpochFilter(time_sec) and host is not NULL and host != \"\""
   },
   {
    "name": "port",
    "query": "select distinct(port) from metrics where cluster = '$cluster' and $__unixEpochFilter(time_sec) and port is not NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory Used vs Total Limit",
   "type": "timeseries",
   "description": "Total_Server_Memory used, out of Maximum_Memory limit.\nUsed memory is broken into data, queries, or internal.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  concat(\n  case when name = 'memsql_variables_maximum_memory' then 'MAXIMUM_MEMORY'\n       when name = 'memsql_status_total_server_memory' then 'Total Memory Used'\n       when name = 'memsql_status_buffer_manager_cached_memory' then 'Cached Memory'\n       when name = 'memsql_status_alloc_table_memory' then 'Data'\n       when name in ('memsql_status_alloc_query_execution',\n                    'memsql_status_alloc_aggregator_query_execution',\n                    'memsql_status_alloc_columnar_query_execution',\n                    'memsql_status_alloc_query_background_tasks',\n                    'memsql_status_alloc_query_execution_temp_table',\n                    'memsql_status_alloc_query_ingest',\n                    'memsql_status_alloc_plan_cache',\n                    'memsql_status_alloc_unit_images',\n                    'memsql_status_alloc_object_code_images',\n                    'memsql_status_alloc_compiled_unit_sections',\n                    'memsql_status_alloc_analyze',\n                    'memsql_status_alloc_arena',\n                    'memsql_status_alloc_autostats',\n                    'memsql_status_alloc_backup_restore',\n                    'memsql_status_alloc_column_store',\n                    'memsql_status_alloc_columnstore_blob_cache',\n                    'memsql_status_alloc_distributed_transaction',\n                    'memsql_status_alloc_dqo_cache',\n                    'memsql_status_alloc_external_formatter',\n                    'memsql_status_alloc_external_functions',\n                    'memsql_status_alloc_fulltext_search',\n                    'memsql_status_alloc_json',\n                    'memsql_status_alloc_mmap_memory',\n                    'memsql_status_alloc_mmap_wasm',\n                    'memsql_status_alloc_parametrizer',\n                    'memsql_status_alloc_pipelines',\n                    'memsql_status_alloc_profile_stats',\n                    'memsql_status_alloc_shared_memory',\n                    'memsql_status_alloc_spatial',\n                    'memsql_status_alloc_spill',\n                    'memsql_status_alloc_stack_first_segmented_array',\n                    'memsql_status_alloc_warnings') then 'Query' else 'Other' end\n  , ' ', trim_host(host), ':', port, ' (', role, ')') as metric,\n  sum(intval) as value\nFROM metrics\nWHERE cluster = '$cluster'\nand extractor = 'memsql'\nand host = '$host'\nand port = '$port'\nand name in ('memsql_variables_maximum_memory',\n            'memsql_status_total_server_memory',\n            'memsql_status_buffer_manager_cached_memory',\n            'memsql_status_alloc_aggregator_query_execution',\n            'memsql_status_alloc_columnar_query_execution',\n            'memsql_status_alloc_query_background_tasks',\n            'memsql_status_alloc_query_execution_temp_table',\n            'memsql_status_alloc_query_ingest',\n            'memsql_status_alloc_column_store',\n            'memsql_status_alloc_analyze',\n            'memsql_status_alloc_arena',\n            'memsql_status_alloc_autostats',\n            'memsql_status_alloc_background_tasks',\n            'memsql_status_alloc_backup_restore',\n            'memsql_status_alloc_client_connection',\n            'memsql_status_alloc_code_generator',\n            'memsql_status_alloc_columnstore_blob_cache',\n            'memsql_status_alloc_databases_list_entry',\n            'memsql_status_alloc_db_tasks',\n            'memsql_status_alloc_distributed_transaction',\n            'memsql_status_alloc_dqo_cache',\n            'memsql_status_alloc_external_formatter',\n            'memsql_status_alloc_fulltext_search',\n            'memsql_status_alloc_global_func',\n            'memsql_status_alloc_json',\n            'memsql_status_alloc_none',\n            'memsql_status_alloc_parametrizer',\n            'memsql_status_alloc_pipelines',\n            'memsql_status_alloc_profile_stats',\n            'memsql_status_alloc_protocol_packet',\n            'memsql_status_alloc_replication',\n            'memsql_status_alloc_security',\n            'memsql_status_alloc_segmented_list',\n            'memsql_status_alloc_sharding_partitions',\n            'memsql_status_alloc_sharding_tables',\n            'memsql_status_alloc_show_statement',\n            'memsql_status_alloc_skynet_consensus',\n            'memsql_status_alloc_snapshot',\n            'memsql_status_alloc_spatial',\n            'memsql_status_alloc_stack_first_segmented_array',\n            'memsql_status_alloc_system_tasks',\n            'memsql_status_alloc_table_metadata_cache',\n            'memsql_status_alloc_transaction',\n            'memsql_status_alloc_warnings',\n            'memsql_status_buffer_manager_unrecycled_memory',\n            'memsql_status_alloc_table_memory',\n            'memsql_status_malloc_active_memory',\n            'memsql_status_alloc_replication_large',\n            'memsql_status_alloc_thread_stacks',\n            'memsql_status_alloc_durability_large',\n            'memsql_status_alloc_external_functions',\n            'memsql_status_alloc_mmap_memory',\n            'memsql_status_alloc_mmap_wasm',\n            'memsql_status_alloc_shared_memory',\n            'memsql_status_alloc_spill',\n            'memsql_status_alloc_thread_signal_handler_altstack',\n            'memsql_status_alloc_unit_ifn_thunks',\n            'memsql_status_total_io_pool_memory',\n            'memsql_status_alloc_compiled_unit_sections',\n            'memsql_status_alloc_object_code_images',\n            'memsql_status_alloc_plan_cache',\n            'memsql_status_alloc_query_execution',\n            'memsql_status_alloc_unit_images')\nand $__unixEpochFilter(time_sec)\ngroup by 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Query Memory Used vs Total Limit",
   "type": "timeseries",
   "description": "Memory used for query execution, code gen, and plancaching, out of Maximum_Memory limit. Query execution can consume the cache, as well as any available memory less than the total limit.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  concat(\n  case \n    when name like 'memsql_status_alloc%' then trim_metric(name, 'memsql_status_alloc_')\n    when name like 'memsql_variables_%' then 'MAXIMUM_MEMORY'\n  end\n  , ' ', trim_host(host), ':', port, ' (', role, ')') as metric,\n  sum(intval) as value\nFROM metrics\nWHERE cluster = '$cluster'\nand extractor = 'memsql'\nand host = '$host'\nand port = '$port'\nand name in ('memsql_variables_maximum_memory',\n            'memsql_status_alloc_query_execution',\n            'memsql_status_alloc_aggregator_query_execution',\n            'memsql_status_alloc_columnar_query_execution',\n            'memsql_status_alloc_query_background_tasks',\n            'memsql_status_alloc_query_execution_temp_table',\n            'memsql_status_alloc_query_ingest',\n            'memsql_status_alloc_plan_cache',\n            'memsql_status_alloc_unit_images',\n            'memsql_status_alloc_object_code_images',\n            'memsql_status_alloc_compiled_unit_sections',\n            'memsql_status_alloc_analyze',\n            'memsql_status_alloc_arena',\n            'memsql_status_alloc_autostats',\n            'memsql_status_alloc_backup_restore',\n            'memsql_status_alloc_column_store',\n            'memsql_status_alloc_columnstore_blob_cache',\n            'memsql_status_alloc_distributed_transaction',\n            'memsql_status_alloc_dqo_cache',\n            'memsql_status_alloc_external_formatter',\n            'memsql_status_alloc_external_functions',\n            'memsql_status_alloc_fulltext_search',\n            'memsql_status_alloc_json',\n            'memsql_status_alloc_mmap_memory',\n            'memsql_status_alloc_mmap_wasm',\n            'memsql_status_alloc_parametrizer',\n            'memsql_status_alloc_pipelines',\n            'memsql_status_alloc_profile_stats',\n            'memsql_status_alloc_shared_memory',\n            'memsql_status_alloc_spatial',\n            'memsql_status_alloc_spill',\n            'memsql_status_alloc_stack_first_segmented_array',\n            'memsql_status_alloc_warnings')\nand $__unixEpochFilter(time_sec)\ngroup by 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Data Memory Used vs Data Limit",
   "type": "timeseries",
   "description": "Table_Memory used, out of Maximum_Table_Memory limit.\nTable_primary and Variable should be the greatest allocators. The others should be small.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  intval as value,\n  concat(\n  case \n    when name like 'memsql_status_alloc_%' then trim_metric(name, 'memsql_status_alloc_')\n    when name like 'memsql_variables_%' then trim_metric(name, 'memsql_variables_')\n  end\n  , ' ', trim_host(host), ':', port, ' (', role, ')') as metric\nFROM metrics\nWHERE cluster = '$cluster'\nand extractor = 'memsql'\nand host = '$host'\nand port = '$port'\nand name in ( 'memsql_variables_maximum_table_memory',\n              'memsql_status_alloc_variable',\n              'memsql_status_alloc_table_primary',\n              'memsql_status_alloc_deleted_version',\n              'memsql_status_alloc_skiplist_tower',\n              'memsql_status_alloc_large_variable',\n              'memsql_status_alloc_hash_buckets',\n              'memsql_status_alloc_internal_key_node',\n              'memsql_status_alloc_table_autostats',\n              'memsql_status_alloc_varbuffer_cache')\nand $__unixEpochFilter(time_sec)\nORDER BY time_sec ASC, value ASC\n"
    }
   ]
  },
  {
   "title": "Internal Memory Allocators vs Total Limit",
   "type": "timeseries",
   "description": "Memory used for internal MemSQL allocations, out of Maximum_Memory limit.\nThe cache holds memory in MemSQL for faster internal allocation (eg for executing queries quickly).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_sec,\n  intval as value,\n  concat(\n  case \n    when name like 'memsql_status_alloc%' then trim_metric(name, 'memsql_status_alloc_')\n    when name like 'memsql_status_buffer_manager_%' then trim_metric(name, 'memsql_status_buffer_manager_')\n    when name like 'memsql_status_%' then trim_metric(name, 'memsql_status_')\n    when name like 'memsql_variables_%' then trim_metric(name, 'memsql_variables_')\n  end\n  , ' ', trim_host(host), ':', port, ' (', role, ')') as metric\nFROM metrics\nWHERE cluster = '$cluster'\nand extractor = 'memsql'\nand host = '$host'\nand port = '$port'\nand name in ('memsql_variables_maximum_memory',\n            'memsql_status_alloc_background_tasks',\n                       'memsql_status_alloc_client_connection',\n                       'memsql_status_alloc_code_generator',\n                       'memsql_status_alloc_databases_list_entry',\n                      'memsql_status_alloc_db_tasks',\n                      'memsql_status_alloc_global_func',\n                      'memsql_status_alloc_none',\n                      'memsql_status_alloc_protocol_packet',\n                      'memsql_status_alloc_replication',\n                      'memsql_status_alloc_security',\n                      'memsql_status_alloc_segmented_list',\n                      'memsql_status_alloc_sharding_partitions',\n                      'memsql_status_alloc_sharding_tables',\n                      'memsql_status_alloc_show_statement',\n                      'memsql_status_alloc_skynet_consensus',\n                      'memsql_status_alloc_snapshot',\n                      'memsql_status_alloc_system_tasks',\n                      'memsql_status_alloc_table_metadata_cache',\n                      'memsql_status_alloc_transaction',\n                      'memsql_status_buffer_manager_unrecycled_memory',\n                      'memsql_status_malloc_active_memory',\n                      'memsql_status_alloc_replication_large',\n                      'memsql_status_alloc_thread_stacks',\n                      'memsql_status_alloc_durability_large',\n                      'memsql_status_alloc_thread_signal_handler_altstack',\n                      'memsql_status_alloc_unit_ifn_thunks',\n                      'memsql_status_total_io_pool_memory')\nand $__unixEpochFilter(time_sec)\nORDER BY time_sec ASC, value ASC\n"
    }
   ]
  }
 ]
}