{
 "title": "SingleStore: Pipeline Summary",
 "tags": [
  "singlestore",
  "sas-speedystore"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select distinct(cluster) from pipeline_metrics where $__timeFilter(ts)"
   },
   {
    "name": "max_ts",
    "query": "select UNIX_TIMESTAMP(max(ts)) from pipeline_metrics  where $__timeFilter(ts)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline State Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT state,\n       COUNT(distinct pipeline_name)  as '' \nFROM pipeline_metrics\nwhere UNIX_TIMESTAMP(ts) = $max_ts and\n      cluster = '$cluster'\ngroup by state"
    }
   ]
  },
  {
   "title": "Historical Pipeline State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select $__timeGroup(ts, $interval) as time,\n       state,\n       count(distinct pipeline_name) as ''\nfrom pipeline_metrics\nwhere cluster = '$cluster' and \n      $__timeFilter(ts)\ngroup by 1,2\norder by 1"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT pipeline_name as PipelineName, \n       database_name as DatabaseName, \n       state as State, \n       create_time as 'Created on', \n       ts as 'Last State Check'\nFROM pipeline_metrics\nwhere UNIX_TIMESTAMP(ts) = '$max_ts'  and\n      cluster = '$cluster'\ngroup by pipeline_name, database_name  "
    }
   ]
  }
 ]
}