{
 "title": "Resource Pool Monitoring",
 "tags": [
  "singlestore",
  "sas-speedystore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "select distinct(cluster) from metrics where $__unixEpochFilter(time_sec)"
   },
   {
    "name": "pool",
    "label": "Resource Pool",
    "query": "select distinct labels::$pool_name\nfrom metrics\nwhere name = 'memsql_resource_pool_status_finished_queries' and\n      $__unixEpochFilter(time_sec) and (cluster='$cluster')"
   },
   {
    "name": "host",
    "query": "select distinct(host) from metrics where host is not NULL and $__unixEpochFilter(time_sec) and (cluster='$cluster')"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Finished Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n            SELECT \n                *, \n                lag(value) OVER w value_l\n            from (\n                  select max(tg) as time,\n                        max(value) as value,\n                        metric,\n                        pool_name\n                  from (\n                        SELECT  time_sec as time,\n                                $__unixEpochGroup(time_sec, $interval) as tg, \n                                host as metric,\n                                labels::$pool_name as pool_name,\n                                value\n                        FROM metrics\n                        WHERE $__unixEpochFilter(time_sec) AND\n                              (cluster = '$cluster') AND\n                              name = 'memsql_resource_pool_status_finished_queries' AND\n                              ('%' in ($pool) or labels::$pool_name in ($pool))\n                        )\n                  group by metric, pool_name, tg) X \n            WINDOW w AS (partition by metric, pool_name order by time))\nselect time, \n       pool_name,\n       sum((value - value_l)) as 'Finished Queries:'\nfrom t\nwhere value_l is not null \n  and value >= value_l\ngroup by time, pool_name\norder by time"
    }
   ]
  },
  {
   "title": "Killed Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n            SELECT \n                *, \n                lag(value) OVER w value_l\n            from (\n                  select max(tg) as time,\n                        max(value) as value,\n                        metric,\n                        pool_name\n                  from (\n                        SELECT  time_sec as time,\n                                $__unixEpochGroup(time_sec, $interval) as tg, \n                                host as metric,\n                                labels::$pool_name as pool_name,\n                                value\n                        FROM metrics\n                        WHERE $__unixEpochFilter(time_sec) AND\n                              (cluster = '$cluster') AND\n                              name = 'memsql_resource_pool_status_killed_queries' AND\n                              ('%' in ($pool) or labels::$pool_name in ($pool))\n                        )\n                  group by metric, pool_name, tg) X \n            WINDOW w AS (partition by metric, pool_name order by time))\nselect time, \n       pool_name,\n       sum((value - value_l)) as 'Killed Queries:'\nfrom t\nwhere value_l is not null \n  and value >= value_l\ngroup by time, pool_name\norder by time"
    }
   ]
  },
  {
   "title": "Queueing Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__unixEpochGroup(time_sec, $interval) as time, \n       labels::$pool_name as pool_name,\n       sum(value) as 'Queueing Queries:'\nFROM metrics\nWHERE $__unixEpochFilter(time_sec) AND\n      (cluster = '$cluster')  AND\n      host not like '%leaf%' and\n      NAME in ('memsql_resource_pool_status_queueing_queries') AND\n      ('%' in ($pool) or labels::$pool_name in ($pool))\ngroup by 1, 2\norder by 1;"
    }
   ]
  },
  {
   "title": "Queue Time per Queued Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "WITH t AS (\n            SELECT \n                *, \n                lag(total_queue_time_ms) OVER w total_queue_time_ms_l\n            from (\n                  select max(tg) as time,\n                        max(case when name = 'memsql_resource_pool_status_total_queue_time_ms' then value end) as total_queue_time_ms,\n                        max(case when name = 'memsql_resource_pool_status_queueing_queries' then value end) as queueing_queries,\n                        metric,\n                        pool_name\n                  from (\n                        SELECT  time_sec as time,\n                                $__unixEpochGroup(time_sec, $interval) as tg, \n                                name,\n                                host as metric,\n                                labels::$pool_name as pool_name,\n                                value\n                        FROM metrics\n                        WHERE $__unixEpochFilter(time_sec) AND\n                              (cluster = '$cluster') AND\n                              name in ('memsql_resource_pool_status_total_queue_time_ms','memsql_resource_pool_status_queueing_queries') AND\n                              ('%' in ($pool) or labels::$pool_name in ($pool))\n                        )\n                  group by metric, pool_name, tg) X \n            WINDOW w AS (partition by metric, pool_name order by time))\nselect time, \n       pool_name,\n       sum((total_queue_time_ms - total_queue_time_ms_l))/sum(queueing_queries) as 'Avg. Queue Time:'\nfrom t\nwhere total_queue_time_ms_l is not null \n  and total_queue_time_ms >= total_queue_time_ms_l\ngroup by time, pool_name\norder by time"
    }
   ]
  }
 ]
}