"""
v4m-mcp: Viya Monitoring MCP server.
 
Exposes a small set of Prometheus-backed tools that an AI assistant can
call to answer common SAS Viya operational questions.
"""
 
import math
import os
import time
 
from fastmcp import FastMCP
from prometheus_api_client import PrometheusConnect
 
mcp = FastMCP("v4m-mcp")
 
prom = PrometheusConnect(
    url=os.getenv(
        "PROMETHEUS_URL",
        "https://prometheus-operated.monitoring.svc:9090",
    ),
    disable_ssl=True,
)
 
# Helpers
 
def _safe_float(value, default: float = 0.0) -> float:
    """Convert a Prometheus value to float, treating NaN as `default`."""
    try:
        v = float(value)
    except (TypeError, ValueError):
        return default
    return default if math.isnan(v) else v
 
 
def duration_seconds(seconds: int) -> str:
    if seconds < 60:
        return f"{seconds}s"
    if seconds < 3600:
        return f"{seconds // 60}m"
    if seconds < 86400:
        return f"{seconds // 3600}h{(seconds % 3600) // 60}m"
    return f"{seconds // 86400}d{(seconds % 86400) // 3600}h"
 
 
def _worst_severity(issues: list) -> str:
    severities = {i.get("severity") for i in issues}
    if "critical" in severities:
        return "critical"
    if "warning" in severities:
        return "warning"
    return "healthy"
 
 
# Tool 1: cluster_health (existing — kept for compatibility)
 
@mcp.tool()
def cluster_health() -> dict:
    """Is the cluster overall healthy?
 
    Question: "How is the cluster doing?" / "Is everything up?"
 
    Scrapes target status, node readiness, and pods
    in CrashLoopBackOff. Use as a first triage tool. For deeper signals
    call `firing_alerts'.
    """
    issues = []
 
    up = prom.custom_query(query="up")
    down_targets = [t for t in up if t["value"][1] == "0"]
 
    ready_nodes = prom.custom_query(
        query='kube_node_status_condition{condition="Ready",status="true"}'
    )
 
    crashloops = prom.custom_query(
        query='kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} == 1'
    )
 
    for target in down_targets:
        m = target["metric"]
        issues.append({
            "type": "target_down",
            "severity": "warning",
            "message": f"Scrape target down: {m.get('job')} ({m.get('instance')})",
            "details": {"job": m.get("job"), "instance": m.get("instance")},
        })
 
    for pod in crashloops:
        m = pod["metric"]
        issues.append({
            "type": "crashloop",
            "severity": "critical",
            "message": f"Pod {m.get('namespace')}/{m.get('pod')} is in CrashLoopBackOff",
            "details": {
                "namespace": m.get("namespace"),
                "pod": m.get("pod"),
                "container": m.get("container"),
            },
        })
 
    return {
        "status": _worst_severity(issues) if issues else "healthy",
        "summary": {
            "healthy_targets": len(up) - len(down_targets),
            "down_targets": len(down_targets),
            "ready_nodes": len(ready_nodes),
            "crashloop_pods": len(crashloops),
        },
        "issues": issues,
    }
 
 
# Tool 2: firing_alerts

@mcp.tool()
def firing_alerts() -> dict:
    """What alerts are currently firing?
  
    Returns the set of Prometheus alerts currently in the `firing` state
    (past their `for:` window), grouped by severity. Call this when the user asks
    what is broken, what alerts are active, or what needs attention.
    """
    # `ALERTS` is auto-generated by Prometheus for every alerting rule.
    # `alertstate="firing"` excludes alerts still inside their `for:` window.
    firing = prom.custom_query(query='ALERTS{alertstate="firing"}')
 
    # `ALERTS_FOR_STATE` records when each alert entered its current state,
    # which lets us compute "firing for: 12m".
    state_starts = prom.custom_query(query="ALERTS_FOR_STATE")
 
    now = time.time()
    start_by_key = {}
    for s in state_starts:
        key = tuple(sorted(
            (k, v) for k, v in s["metric"].items()
            if k not in ("__name__", "alertstate")
        ))
        start_by_key[key] = _safe_float(s["value"][1])
 
    issues = []
    sev_counts = {"critical": 0, "warning": 0, "info": 0, "other": 0}
 
    for alert in firing:
        labels = alert["metric"]
        alertname = labels.get("alertname", "Unknown")
        severity = labels.get("severity", "other").lower()
        if severity not in sev_counts:
            severity = "other"
        sev_counts[severity] += 1
 
        # Compute firing duration if we have a start timestamp.
        key = tuple(sorted(
            (k, v) for k, v in labels.items()
            if k not in ("__name__", "alertstate")
        ))
        firing_for_seconds = None
        if key in start_by_key and start_by_key[key] > 0:
            firing_for_seconds = max(0, int(now - start_by_key[key]))
 
        # Build a human-readable message from the most relevant labels.
        target_parts = []
        if "namespace" in labels:
            target_parts.append(f"ns={labels['namespace']}")
        if "pod" in labels:
            target_parts.append(f"pod={labels['pod']}")
        if "node" in labels and "pod" not in labels:
            target_parts.append(f"node={labels['node']}")
        target_str = f" on {', '.join(target_parts)}" if target_parts else ""
 
        duration_str = (
            f" (firing for {duration_seconds(firing_for_seconds)})"
            if firing_for_seconds is not None else ""
        )
 
        # `severity` is normalized to 'critical' for sort priority 
        sort_priority = {"critical": 0, "warning": 1, "info": 2, "other": 3}[severity]
 
        issues.append({
            "_priority": sort_priority,
            "severity": severity,
            "message": f"{alertname}{target_str}{duration_str}",
            "details": {
                "alertname": alertname,
                "labels": {
                    k: v for k, v in labels.items()
                    if k not in ("__name__", "alertstate")
                },
                "firing_for_seconds": firing_for_seconds,
            },
        })
 
    issues.sort(key=lambda i: i.pop("_priority"))
 
    if sev_counts["critical"]:
        status = "critical"
    elif sev_counts["warning"] or sev_counts["info"] or sev_counts["other"]:
        status = "warning"
    else:
        status = "healthy"
 
    return {
        "status": status,
        "summary": {
            "total_firing": len(issues),
            "critical": sev_counts["critical"],
            "warning": sev_counts["warning"],
            "info": sev_counts["info"],
            "other": sev_counts["other"],
        },
        "issues": issues,
    }
 
 
if __name__ == "__main__":
    mcp.run(
        transport="http",
        host="0.0.0.0",
        port=int(os.getenv("PORT", "8000")),
    )