"""
v4m-mcp: Viya Monitoring MCP server.
 
Exposes a small set of Prometheus-backed tools that an AI assistant can
call to answer common SAS Viya operational questions.
"""
 
import math
import os
import re
import time
from datetime import datetime, timedelta

from fastmcp import FastMCP
from prometheus_api_client import PrometheusConnect
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware

from rag import DocIndex  # documentation retrieval engine

mcp = FastMCP("v4m-mcp")
 
prom = PrometheusConnect(
    url=os.getenv(
        "PROMETHEUS_URL",
        "https://prometheus-operated.monitoring.svc:9090",
    ),
    disable_ssl=True,
)
 
# Documentation index — built lazily so a docs/embeddings problem can never
# take down the Prometheus tools. The first search_docs() call builds it (or
# loads the on-disk cache); later calls are instant.
_docs_index = None
 
 
def _docs():
    global _docs_index
    if _docs_index is None:
        _docs_index = DocIndex.from_env()
    return _docs_index
 
 
# Helpers
 
def _safe_float(value, default: float = 0.0) -> float:
    """Convert a Prometheus value to float, treating NaN as `default`."""
    try:
        v = float(value)
    except (TypeError, ValueError):
        return default
    return default if math.isnan(v) else v
 
 
def duration_seconds(seconds: int) -> str:
    if seconds < 60:
        return f"{seconds}s"
    if seconds < 3600:
        return f"{seconds // 60}m"
    if seconds < 86400:
        return f"{seconds // 3600}h{(seconds % 3600) // 60}m"
    return f"{seconds // 86400}d{(seconds % 86400) // 3600}h"
 
 
def _worst_severity(issues: list) -> str:
    severities = {i.get("severity") for i in issues}
    if "critical" in severities:
        return "critical"
    if "warning" in severities:
        return "warning"
    return "healthy"
 
 
# Tool 1: cluster_health (existing — kept for compatibility)
 
@mcp.tool()
def cluster_health() -> dict:
    """Is the cluster overall healthy?
 
    Question: "How is the cluster doing?" / "Is everything up?"
 
    Scrapes target status, node readiness, and pods
    in CrashLoopBackOff. Use as a first triage tool. For deeper signals
    call `firing_alerts'.
    """
    issues = []
 
    up = prom.custom_query(query="up")
    down_targets = [t for t in up if t["value"][1] == "0"]
 
    ready_nodes = prom.custom_query(
        query='kube_node_status_condition{condition="Ready",status="true"}'
    )
 
    crashloops = prom.custom_query(
        query='kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} == 1'
    )
 
    for target in down_targets:
        m = target["metric"]
        issues.append({
            "type": "target_down",
            "severity": "warning",
            "message": f"Scrape target down: {m.get('job')} ({m.get('instance')})",
            "details": {"job": m.get("job"), "instance": m.get("instance")},
        })
 
    for pod in crashloops:
        m = pod["metric"]
        issues.append({
            "type": "crashloop",
            "severity": "critical",
            "message": f"Pod {m.get('namespace')}/{m.get('pod')} is in CrashLoopBackOff",
            "details": {
                "namespace": m.get("namespace"),
                "pod": m.get("pod"),
                "container": m.get("container"),
            },
        })
 
    return {
        "status": _worst_severity(issues) if issues else "healthy",
        "summary": {
            "healthy_targets": len(up) - len(down_targets),
            "down_targets": len(down_targets),
            "ready_nodes": len(ready_nodes),
            "crashloop_pods": len(crashloops),
        },
        "issues": issues,
    }
 
 
# Tool 2: firing_alerts

@mcp.tool()
def firing_alerts() -> dict:
    """What alerts are currently firing?
  
    Returns the set of Prometheus alerts currently in the `firing` state
    (past their `for:` window), grouped by severity. Call this when the user asks
    what is broken, what alerts are active, or what needs attention.
    """
    # `ALERTS` is auto-generated by Prometheus for every alerting rule.
    # `alertstate="firing"` excludes alerts still inside their `for:` window.
    firing = prom.custom_query(query='ALERTS{alertstate="firing"}')
 
    # `ALERTS_FOR_STATE` records when each alert entered its current state,
    # which lets us compute "firing for: 12m".
    state_starts = prom.custom_query(query="ALERTS_FOR_STATE")
 
    now = time.time()
    start_by_key = {}
    for s in state_starts:
        key = tuple(sorted(
            (k, v) for k, v in s["metric"].items()
            if k not in ("__name__", "alertstate")
        ))
        start_by_key[key] = _safe_float(s["value"][1])
 
    issues = []
    sev_counts = {"critical": 0, "warning": 0, "info": 0, "other": 0}
 
    for alert in firing:
        labels = alert["metric"]
        alertname = labels.get("alertname", "Unknown")
        severity = labels.get("severity", "other").lower()
        if severity not in sev_counts:
            severity = "other"
        sev_counts[severity] += 1
 
        # Compute firing duration if we have a start timestamp.
        key = tuple(sorted(
            (k, v) for k, v in labels.items()
            if k not in ("__name__", "alertstate")
        ))
        firing_for_seconds = None
        if key in start_by_key and start_by_key[key] > 0:
            firing_for_seconds = max(0, int(now - start_by_key[key]))
 
        # Build a human-readable message from the most relevant labels.
        target_parts = []
        if "namespace" in labels:
            target_parts.append(f"ns={labels['namespace']}")
        if "pod" in labels:
            target_parts.append(f"pod={labels['pod']}")
        if "node" in labels and "pod" not in labels:
            target_parts.append(f"node={labels['node']}")
        target_str = f" on {', '.join(target_parts)}" if target_parts else ""
 
        duration_str = (
            f" (firing for {duration_seconds(firing_for_seconds)})"
            if firing_for_seconds is not None else ""
        )
 
        # `severity` is normalized to 'critical' for sort priority 
        sort_priority = {"critical": 0, "warning": 1, "info": 2, "other": 3}[severity]
 
        issues.append({
            "_priority": sort_priority,
            "severity": severity,
            "message": f"{alertname}{target_str}{duration_str}",
            "details": {
                "alertname": alertname,
                "labels": {
                    k: v for k, v in labels.items()
                    if k not in ("__name__", "alertstate")
                },
                "firing_for_seconds": firing_for_seconds,
            },
        })
 
    issues.sort(key=lambda i: i.pop("_priority"))
 
    if sev_counts["critical"]:
        status = "critical"
    elif sev_counts["warning"] or sev_counts["info"] or sev_counts["other"]:
        status = "warning"
    else:
        status = "healthy"
 
    return {
        "status": status,
        "summary": {
            "total_firing": len(issues),
            "critical": sev_counts["critical"],
            "warning": sev_counts["warning"],
            "info": sev_counts["info"],
            "other": sev_counts["other"],
        },
        "issues": issues,
    }
 
 
# Live-metric + no-data-diagnosis tools
#
# These give the agent direct eyes on the data: it can run the exact PromQL a
# panel uses, and when a query comes back empty it can walk the causal chain
# (query -> metric -> label matchers -> scrape targets) instead of guessing.

_METRIC_NAME_RE = re.compile(r"[a-zA-Z_:][a-zA-Z0-9_:]*$")
_LABEL_NAME_RE = re.compile(r"[a-zA-Z_][a-zA-Z0-9_]*$")

_PROMQL_RESERVED = {
    # keywords / modifiers
    "by", "without", "on", "ignoring", "group_left", "group_right",
    "and", "or", "unless", "offset", "bool",
    # common functions (bare tokens followed by '(' are filtered separately;
    # this catches them in edge cases as well)
    "rate", "irate", "increase", "delta", "idelta", "deriv", "predict_linear",
    "sum", "avg", "min", "max", "count", "topk", "bottomk", "quantile",
    "stddev", "stdvar", "count_values", "histogram_quantile",
    "sum_over_time", "avg_over_time", "min_over_time", "max_over_time",
    "count_over_time", "last_over_time", "present_over_time", "quantile_over_time",
    "abs", "absent", "absent_over_time", "ceil", "floor", "round",
    "clamp", "clamp_max", "clamp_min", "changes", "resets", "exp", "ln",
    "log2", "log10", "scalar", "sort", "sort_desc", "sqrt", "time",
    "timestamp", "vector", "label_replace", "label_join",
    "year", "month", "minute", "hour", "day_of_month", "day_of_week",
    "days_in_month",
}


def _parse_window(window: str) -> int:
    """'30m' / '1h' / '2d' -> seconds; falls back to 1h on anything odd."""
    m = re.fullmatch(r"(\d+)([smhdw])", (window or "").strip())
    if not m:
        return 3600
    mult = {"s": 1, "m": 60, "h": 3600, "d": 86400, "w": 604800}[m.group(2)]
    return int(m.group(1)) * mult


def _series_label(metric: dict) -> str:
    name = metric.get("__name__", "")
    labels = ", ".join(
        f"{k}={v}" for k, v in sorted(metric.items()) if k != "__name__"
    )
    text = f"{name}{{{labels}}}" if labels else (name or "{}")
    return text if len(text) <= 160 else text[:160] + "..."


def _downsample(points: list, max_points: int = 20) -> list:
    if len(points) <= max_points:
        return points
    stride = len(points) / max_points
    sampled = [points[int(i * stride)] for i in range(max_points - 1)]
    sampled.append(points[-1])
    return sampled


def _summarize_matrix(series_list: list, max_series: int = 8) -> dict:
    """Reduce a Prometheus range-query result to LLM-sized statistics."""
    summary = {"series_count": len(series_list), "series": []}

    for series in series_list[:max_series]:
        raw = [(int(_safe_float(ts)), _safe_float(v)) for ts, v in series.get("values", [])]
        vals = [v for _, v in raw]
        if not vals:
            continue

        avg = sum(vals) / len(vals)
        quarter = max(1, len(vals) // 4)
        head_avg = sum(vals[:quarter]) / quarter
        tail_avg = sum(vals[-quarter:]) / quarter
        if head_avg == 0 and tail_avg == 0:
            trend = "flat_at_zero"
        elif head_avg == 0:
            trend = "rising"
        else:
            change = (tail_avg - head_avg) / abs(head_avg)
            trend = "rising" if change > 0.15 else "falling" if change < -0.15 else "flat"

        summary["series"].append({
            "labels": _series_label(series.get("metric", {})),
            "points": len(vals),
            "min": round(min(vals), 4),
            "max": round(max(vals), 4),
            "avg": round(avg, 4),
            "last": round(vals[-1], 4),
            "trend": trend,
            "sampled_values": [[ts, round(v, 4)] for ts, v in _downsample(raw)],
        })

    if len(series_list) > max_series:
        summary["truncated"] = (
            f"showing {max_series} of {len(series_list)} series; "
            "aggregate (sum/avg/topk) in the query to see the rest"
        )
    return summary


def _count_query(query: str) -> int:
    """Evaluate a count(...) query; -1 signals the query itself errored."""
    try:
        result = prom.custom_query(query=query)
    except Exception:
        return -1
    if not result:
        return 0
    return int(_safe_float(result[0]["value"][1]))


def _extract_selectors(expr: str) -> list:
    """Pull (metric, [matchers]) pairs out of a PromQL expression.

    Heuristic, not a full parser: handles metric{...} selectors and bare
    metric names; a comma inside a label VALUE will split a matcher wrongly.
    """
    selectors = []
    braced_names = set()

    for m in re.finditer(r"([a-zA-Z_:][a-zA-Z0-9_:]*)\s*\{([^}]*)\}", expr):
        name = m.group(1)
        if name.lower() in _PROMQL_RESERVED:
            continue
        braced_names.add(name)
        matchers = [x.strip() for x in m.group(2).split(",") if x.strip()]
        selectors.append({"metric": name, "matchers": matchers})

    for m in re.finditer(r"[a-zA-Z_:][a-zA-Z0-9_:]*", expr):
        token = m.group(0)
        if token in braced_names or token.lower() in _PROMQL_RESERVED:
            continue
        rest = expr[m.end():]
        if re.match(r"\s*[({]", rest):  # function call or already-handled selector
            continue
        if not _METRIC_NAME_RE.fullmatch(token) or token.isdigit():
            continue
        if any(s["metric"] == token for s in selectors):
            continue
        selectors.append({"metric": token, "matchers": []})

    return selectors[:3]


@mcp.tool()
def query_prometheus(expr: str, window: str = "1h") -> dict:
    """Run a PromQL query and return a compact statistical summary of the live data.

    Use this to READ THE ACTUAL METRIC DATA — e.g. run a dashboard panel's own
    query to see what the user is looking at, check a metric's current value,
    or examine behavior over time. Returns per-series min/max/avg/last, a
    trend direction, and ~20 downsampled points per series.

    Args:
        expr: A PromQL expression, e.g.
            'sum(rate(container_cpu_usage_seconds_total{namespace="viya"}[5m]))'.
        window: Lookback range such as '30m', '1h', '6h', '1d' (default '1h').
    """
    seconds = _parse_window(window)
    end = datetime.now()
    start = end - timedelta(seconds=seconds)
    step = max(15, seconds // 100)

    try:
        result = prom.custom_query_range(
            query=expr, start_time=start, end_time=end, step=str(step)
        )
    except Exception as exc:
        return {
            "expr": expr,
            "error": f"Query failed to evaluate: {exc}",
            "hint": "Check the PromQL syntax; if the syntax is valid, call explain_empty_query.",
        }

    summary = _summarize_matrix(result)
    summary["expr"] = expr
    summary["window"] = window
    if summary["series_count"] == 0:
        summary["note"] = (
            "The query evaluated successfully but returned no series over the "
            "window. Call explain_empty_query to find out why."
        )
    return summary


@mcp.tool()
def check_metric_exists(metric: str) -> dict:
    """Check whether a metric exists in Prometheus now, and when it was last seen.

    Use when a panel or query shows no data and you need to know if the
    underlying metric is present at all, recently disappeared, or was never
    scraped (wrong name, exporter missing).

    Args:
        metric: A bare metric name, e.g. 'kube_pod_status_phase'.
    """
    if not _METRIC_NAME_RE.fullmatch(metric):
        return {"error": f"'{metric}' is not a valid Prometheus metric name."}

    now_count = _count_query(f"count({metric})")
    day_count = _count_query(f"count(count_over_time({metric}[1d]))")
    week_count = _count_query(f"count(count_over_time({metric}[7d]))")

    if now_count > 0:
        verdict = "present"
    elif day_count > 0:
        verdict = "disappeared_recently (existed within the last 24h)"
    elif week_count > 0:
        verdict = "stale (last seen more than 24h ago, within 7d)"
    else:
        verdict = "absent (not seen in 7d — wrong metric name, or its exporter was never scraped)"

    return {
        "metric": metric,
        "series_now": now_count,
        "series_seen_last_24h": day_count,
        "series_seen_last_7d": week_count,
        "verdict": verdict,
    }


@mcp.tool()
def list_failing_targets() -> dict:
    """List Prometheus scrape targets that are not healthy, with their last error.

    Use to check the COLLECTION layer: when a metric is missing or stale, a
    down exporter/scrape target is a common root cause. Pair with the pod
    diagnostics tools to see whether the exporter's pod itself is unhealthy.
    """
    try:
        resp = prom._session.get(
            f"{prom.url}/api/v1/targets",
            params={"state": "active"},
            verify=False,
            timeout=15,
        )
        targets = resp.json()["data"]["activeTargets"]
    except Exception as exc:
        return {"error": f"Could not read scrape targets: {exc}"}

    failing = [t for t in targets if t.get("health") != "up"]
    return {
        "active_targets": len(targets),
        "down_targets": len(failing),
        "failing": [
            {
                "job": t.get("labels", {}).get("job"),
                "instance": t.get("labels", {}).get("instance"),
                "health": t.get("health"),
                "last_error": (t.get("lastError") or "")[:300],
                "last_scrape": t.get("lastScrape"),
            }
            for t in failing[:25]
        ],
    }


@mcp.tool()
def explain_empty_query(expr: str) -> dict:
    """Diagnose WHY a PromQL query returns no data.

    Decomposes the query into its metric selectors, then checks each layer:
    does the metric exist at all, did it exist recently, and which individual
    label matcher eliminates every series. Use whenever a panel shows
    "No data" or query_prometheus reports zero series.

    Args:
        expr: The PromQL expression that is returning nothing.
    """
    try:
        current = prom.custom_query(query=expr)
    except Exception as exc:
        return {
            "verdict": "query_error",
            "error": str(exc),
            "explanation": "The query fails to evaluate — a syntax or type error, not missing data.",
        }

    if current:
        return {
            "verdict": "has_data",
            "series_now": len(current),
            "explanation": (
                "The query returns data right now. If a panel is empty, suspect the "
                "panel's time range, datasource, or a dashboard variable instead."
            ),
        }

    selectors = _extract_selectors(expr)
    if not selectors:
        return {
            "verdict": "unknown",
            "explanation": "Could not extract metric selectors from the expression; inspect it manually.",
        }

    findings = []
    for sel in selectors:
        name, matchers = sel["metric"], sel["matchers"]
        entry = {"metric": name}

        base_count = _count_query(f"count({name})")
        entry["series_without_matchers"] = base_count

        if base_count <= 0:
            week_count = _count_query(f"count(count_over_time({name}[7d]))")
            entry["series_seen_last_7d"] = week_count
            entry["finding"] = (
                "metric existed within the last 7d but has no series now — its exporter "
                "likely stopped; check list_failing_targets"
                if week_count > 0
                else "metric not seen in 7d — wrong metric name, or its exporter is not scraped at all"
            )
            findings.append(entry)
            continue

        dead_matchers = []
        for matcher in matchers[:8]:
            if _count_query(f"count({name}{{{matcher}}})") == 0:
                dead_matchers.append(matcher)

        if dead_matchers:
            entry["matchers_matching_nothing"] = dead_matchers
            label = re.split(r"!?=~?", dead_matchers[0])[0].strip()
            if _LABEL_NAME_RE.fullmatch(label):
                try:
                    grouped = prom.custom_query(query=f"count by ({label}) ({name})")
                    entry[f"actual_{label}_values"] = sorted(
                        {g["metric"].get(label, "(none)") for g in grouped}
                    )[:10]
                except Exception:
                    pass
            entry["finding"] = (
                f"metric exists ({base_count} series) but these matchers match nothing: "
                f"{dead_matchers} — compare with the actual label values"
            )
        else:
            entry["finding"] = (
                "metric and every individual matcher match series, so the empty result "
                "comes from the matcher COMBINATION, a range function over too little "
                "data, or vector matching between series that share no labels"
            )
        findings.append(entry)

    return {
        "verdict": "diagnosed",
        "expr": expr,
        "findings": findings,
        "note": "Selector analysis is heuristic; a comma inside a label value can confuse it.",
    }


_NAMESPACE_RE = re.compile(r"[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$")


def _label_selector(*matchers: str) -> str:
    parts = [m for m in matchers if m]
    return "{" + ",".join(parts) + "}" if parts else ""


@mcp.tool()
def recent_changes(namespace: str = "", window: str = "1h") -> dict:
    """What changed in the cluster recently: restarts, new pods, rollouts, OOM kills.

    Use to answer "what changed?" or "did a deploy cause this?" — correlate a
    metric anomaly with cluster changes in the same window. Call it with the
    window in which the anomaly started (e.g. the spike began 30 minutes ago
    -> window='45m').

    Args:
        namespace: Restrict to one namespace (default: all namespaces).
        window: How far back to look, e.g. '30m', '1h', '6h' (default '1h').
    """
    if namespace and not _NAMESPACE_RE.fullmatch(namespace):
        return {"error": f"'{namespace}' is not a valid namespace name."}

    seconds = _parse_window(window)
    now = time.time()
    cutoff = now - seconds
    ns_matcher = f'namespace="{namespace}"' if namespace else ""

    changes = {"window": window, "namespace": namespace or "(all)"}

    # Container restarts within the window.
    try:
        restarts = prom.custom_query(
            query=(
                "increase(kube_pod_container_status_restarts_total"
                + _label_selector(ns_matcher)
                + f"[{window}]) > 0"
            )
        )
        changes["container_restarts"] = [
            {
                "namespace": r["metric"].get("namespace"),
                "pod": r["metric"].get("pod"),
                "container": r["metric"].get("container"),
                "restarts": int(round(_safe_float(r["value"][1]))),
            }
            for r in restarts[:15]
        ]
    except Exception as exc:
        changes["container_restarts"] = f"query failed: {exc}"

    # Pods created within the window.
    try:
        created = prom.custom_query(query="kube_pod_created" + _label_selector(ns_matcher))
        new_pods = sorted(
            (
                {
                    "namespace": r["metric"].get("namespace"),
                    "pod": r["metric"].get("pod"),
                    "created_seconds_ago": int(now - _safe_float(r["value"][1])),
                }
                for r in created
                if _safe_float(r["value"][1]) >= cutoff
            ),
            key=lambda p: p["created_seconds_ago"],
        )
        changes["new_pods"] = new_pods[:15]
    except Exception as exc:
        changes["new_pods"] = f"query failed: {exc}"

    # New ReplicaSets = deployment rollouts (RS name minus its hash suffix
    # approximates the Deployment name).
    try:
        replicasets = prom.custom_query(
            query="kube_replicaset_created" + _label_selector(ns_matcher)
        )
        rollouts = sorted(
            (
                {
                    "namespace": r["metric"].get("namespace"),
                    "replicaset": r["metric"].get("replicaset"),
                    "deployment": (r["metric"].get("replicaset") or "").rsplit("-", 1)[0],
                    "created_seconds_ago": int(now - _safe_float(r["value"][1])),
                }
                for r in replicasets
                if _safe_float(r["value"][1]) >= cutoff
            ),
            key=lambda p: p["created_seconds_ago"],
        )
        changes["rollouts"] = rollouts[:15]
    except Exception as exc:
        changes["rollouts"] = f"query failed: {exc}"

    # Containers whose last termination was an OOM kill.
    try:
        oom = prom.custom_query(
            query=(
                "kube_pod_container_status_last_terminated_reason"
                + _label_selector('reason="OOMKilled"', ns_matcher)
                + " == 1"
            )
        )
        changes["oom_killed_containers"] = [
            {
                "namespace": r["metric"].get("namespace"),
                "pod": r["metric"].get("pod"),
                "container": r["metric"].get("container"),
            }
            for r in oom[:15]
        ]
    except Exception as exc:
        changes["oom_killed_containers"] = f"query failed: {exc}"

    def _count(value) -> int:
        return len(value) if isinstance(value, list) else 0

    total = sum(
        _count(changes.get(k))
        for k in ("container_restarts", "new_pods", "rollouts", "oom_killed_containers")
    )
    changes["summary"] = (
        f"{total} change(s) detected in the last {window}"
        if total
        else f"No restarts, new pods, rollouts, or OOM kills detected in the last {window}."
    )
    return changes


@mcp.tool()
def list_viya_namespaces() -> dict:
    """Find the namespace(s) where SAS Viya is actually deployed.

    Viya namespaces are customer-named (often opaque, e.g. 'd122472'), so when
    the user says "the Viya namespace", call this FIRST instead of assuming
    namespace="viya": it looks for namespaces running sas-* workloads.
    """
    try:
        result = prom.custom_query(query='count by (namespace) (kube_pod_info{pod=~"sas-.*"})')
    except Exception as exc:
        return {"error": f"Query failed: {exc}"}

    namespaces = sorted(
        (
            {
                "namespace": r["metric"].get("namespace"),
                "sas_pods": int(_safe_float(r["value"][1])),
            }
            for r in result
        ),
        key=lambda n: -n["sas_pods"],
    )
    if not namespaces:
        return {
            "viya_namespaces": [],
            "note": "No namespaces with sas-* pods found — Viya may not be deployed or not scraped.",
        }
    return {
        "viya_namespaces": namespaces[:5],
        "note": "Namespaces currently running sas-* pods, most pods first.",
    }


@mcp.tool()
def list_pods(namespace: str, detail: bool = False) -> dict:
    """List what runs in a namespace: workloads (default) or individual pods.

    Use for "what pods are running in X" or "what does each pod do". The
    default workload-grouped view covers EVERY pod in the namespace with no
    truncation (one row per Deployment/StatefulSet/etc. with pod/ready/restart
    counts) — pair the workload names with search_docs to explain each
    component's function. Pass detail=true only when individual pod names are
    needed (capped at 60 pods).

    Args:
        namespace: The namespace to list, e.g. 'monitoring' or a Viya
            namespace from list_viya_namespaces.
        detail: false (default) = one row per workload, complete coverage;
            true = individual pods, capped at 60.
    """
    if not _NAMESPACE_RE.fullmatch(namespace):
        return {"error": f"'{namespace}' is not a valid namespace name."}

    ns = f'namespace="{namespace}"'
    try:
        info = prom.custom_query(query="kube_pod_info" + _label_selector(ns))
        owners = prom.custom_query(query="kube_pod_owner" + _label_selector(ns))
        ready = prom.custom_query(
            query="kube_pod_status_ready" + _label_selector(ns, 'condition="true"')
        )
        restarts = prom.custom_query(
            query="sum by (pod) (kube_pod_container_status_restarts_total" + _label_selector(ns) + ")"
        )
    except Exception as exc:
        return {"error": f"Query failed: {exc}"}

    owner_by_pod = {
        r["metric"].get("pod"): (
            r["metric"].get("owner_kind", ""),
            r["metric"].get("owner_name", ""),
        )
        for r in owners
    }
    ready_by_pod = {r["metric"].get("pod"): _safe_float(r["value"][1]) >= 1 for r in ready}
    restarts_by_pod = {
        r["metric"].get("pod"): int(_safe_float(r["value"][1])) for r in restarts
    }

    pods = []
    for r in info:
        pod = r["metric"].get("pod")
        kind, owner = owner_by_pod.get(pod, ("", ""))
        # A ReplicaSet owner's name minus its hash approximates the Deployment.
        workload = owner.rsplit("-", 1)[0] if kind == "ReplicaSet" and "-" in owner else owner
        pods.append({
            "pod": pod,
            "workload": workload or pod,
            "owner_kind": kind,
            "node": r["metric"].get("node"),
            "ready": ready_by_pod.get(pod, False),
            "restarts": restarts_by_pod.get(pod, 0),
        })

    pods.sort(key=lambda p: (p["workload"], p["pod"]))

    if detail:
        out = {"namespace": namespace, "pod_count": len(pods), "pods": pods[:60]}
        if len(pods) > 60:
            out["truncated"] = (
                f"showing 60 of {len(pods)} pods — the default workload view "
                "(detail=false) covers all of them"
            )
        return out

    workloads: dict = {}
    for p in pods:
        entry = workloads.setdefault(
            (p["workload"], p["owner_kind"]),
            {"workload": p["workload"], "kind": p["owner_kind"], "pods": 0, "ready": 0, "restarts": 0},
        )
        entry["pods"] += 1
        entry["ready"] += 1 if p["ready"] else 0
        entry["restarts"] += p["restarts"]

    return {
        "namespace": namespace,
        "pod_count": len(pods),
        "workload_count": len(workloads),
        "workloads": sorted(workloads.values(), key=lambda w: w["workload"]),
        "note": "One row per workload, covering all pods. Call with detail=true for individual pod names.",
    }


# Tool 3: search_docs (RAG as a tool)
 
@mcp.tool()
def search_docs(query: str, top_k: int = 5) -> str:
    """Search the SAS Viya Monitoring documentation for relevant passages.
 
    Call this for conceptual or how-to questions the Prometheus tools can't
    answer from live metrics: what a component does, how to configure or deploy
    it, what an alert means, or troubleshooting steps. Returns ranked passages,
    each with its source file/heading and a relevance score.
 
    Args:
        query: A natural-language question or keywords to look up in the docs.
        top_k: How many passages to return (default 5; keep it <= ~10).
    """
    try:
        return _docs().search(query, top_k)
    except Exception as exc:
        # Degrade gracefully: a docs/embeddings issue must never surface as a
        # server error to the operational tools.
        return f"Documentation search is currently unavailable: {exc}"
 
 
@mcp.tool()
def docs_index_stats() -> str:
    """Report how many documentation chunks are indexed, and from which sources."""
    try:
        idx = _docs()
    except Exception as exc:
        return f"Documentation index is not available: {exc}"
    sources = sorted({c.source for c in idx.chunks})
    return f"{len(idx.chunks)} chunks indexed from {len(sources)} source(s):\n" + "\n".join(sources)
 
 
if __name__ == "__main__":
    if os.getenv("WARM_INDEX", "").lower() in ("1", "true", "yes"):
        try:
            _docs()
            print(f"[v4m-mcp] docs index ready: {len(_docs_index.chunks)} chunks")
        except Exception as exc:
            print(f"[v4m-mcp] docs index warm-up skipped: {exc}")
 
    # The Grafana chatbot plugin calls this server directly from the browser
    # (no backend proxy), so it needs CORS. ALLOWED_ORIGIN is comma-separated;
    # defaults to "*" to match the already-accepted no-auth posture of this
    # endpoint — tighten to the real Grafana origin(s) when auth is added.
    allowed_origins = [
        o.strip() for o in os.getenv("ALLOWED_ORIGIN", "*").split(",") if o.strip()
    ]

    mcp.run(
        transport="http",
        host="0.0.0.0",
        port=int(os.getenv("PORT", "8000")),
        middleware=[
            Middleware(
                CORSMiddleware,
                allow_origins=allowed_origins,
                allow_methods=["GET", "POST", "OPTIONS", "DELETE"],
                allow_headers=["*"],
                # Browsers hide cross-origin response headers from JS fetch()
                # unless explicitly exposed — the MCP streamable-http client
                # reads mcp-session-id from the initialize response to tag
                # every subsequent request. Without this, the session ID is
                # silently dropped and every request after initialize fails.
                expose_headers=["mcp-session-id"],
            ),
        ],
    )