image:
  tag: 1.7.9
podAnnotations: 
  fluentbit.io/parser: fluentbit
podLabels:
  fbout: es
serviceMonitor:
  enabled: false
extraVolumeMounts:
- mountPath: /fluent-bit/etc/viya-parsers.conf
  name: parsers-config
  subPath: viya-parsers.conf
- mountPath: /var/log/fb_buffer
  name: fb-buffer
extraVolumes:
- configMap:
    defaultMode: 420
    name: fb-viya-parsers
  name: parsers-config
- name: fb-buffer
  emptyDir: {}
fullConfigMap: false
existingConfigMap: fb-fluent-bit-config

env:
   - name: ES_LOGCOLLECTOR_USER
     valueFrom:
       secretKeyRef:
         name: internal-user-logcollector
         key: username
   - name: ES_LOGCOLLECTOR_PASSWD
     valueFrom:
       secretKeyRef:
         name: internal-user-logcollector
         key: password
envFrom:
   - configMapRef:
        name: fb-env-vars


# Be very tolerant
tolerations:
- operator: "Exists"
