# Override values for the Fluent Bit helm chart
#
# Chart:  https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/Chart.yaml
# Default values: https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml

image:
  tag: 1.8.7
podAnnotations: 
  fluentbit.io/parser: fluentbit
podLabels:
  fbout: es
serviceMonitor:
  enabled: false
extraVolumeMounts:
- mountPath: /fluent-bit/etc/viya-parsers.conf
  name: parsers-config
  subPath: viya-parsers.conf
extraVolumes:
- configMap:
    defaultMode: 420
    name: fb-viya-parsers
  name: parsers-config
fullConfigMap: false
existingConfigMap: fb-fluent-bit-config

env:
   - name: ES_LOGCOLLECTOR_USER
     valueFrom:
       secretKeyRef:
         name: internal-user-logcollector
         key: username
   - name: ES_LOGCOLLECTOR_PASSWD
     valueFrom:
       secretKeyRef:
         name: internal-user-logcollector
         key: password
envFrom:
   - configMapRef:
        name: fb-env-vars


# Be very tolerant
tolerations:
- operator: "Exists"

resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
