[INPUT]
   Name                opentelemetry
   Listen              0.0.0.0
   Port                4318
   Tag                 viya_otel
   Buffer_chunk_size   1M
   Buffer_max_size     10M

[OUTPUT]
   Name                opentelemetry
   Host                v4m-tempo.${MON_NS}
   Port                4318
   Match               *
   Traces_uri          /v1/traces
   compress            gzip
   retry_limit         5
   workers             2
   net.connect_timeout 10s
   net.io_timeout      60s
   log_response_payload false
