# Chart: https://github.com/grafana/helm-charts/tree/main/charts/grafana
# Default Values: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

readinessProbe:
  httpGet:
    scheme: HTTPS
    port: 3001
livenessProbe:
  httpGet:
    scheme: HTTPS
    port: 3001

extraSecretMounts:
- name: v4m-grafana-tls
  mountPath: /cert
  secretName: v4m-grafana-tls-secret
  readOnly: true
  subPath: ""

sidecar:
  dashboards:
    reloadURL: "https://localhost:3001/api/admin/provisioning/dashboards/reload"    
    env:
      REQ_SKIP_TLS_VERIFY: true
  datasources:
    defaultDatasourceEnabled: false
    reloadURL: "https://localhost:3001/api/admin/provisioning/datasources/reload"    
    env:
      REQ_SKIP_TLS_VERIFY: true

service:
  enabled: false

"grafana.ini":
  server:
    protocol: https
    http_port: 3001
    cert_file: /cert/tls.crt
    cert_key: /cert/tls.key
