## NOTE: Refer to https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/stable/ARTIFACT_INVENTORY.md
##       to identify the current Helm chart version in use by this project.  The links below point to
##       the 'main' branch as a general reference and the contents will likely differ to some degree.
##
## Chart: https://github.com/grafana-community/helm-charts/tree/main/charts/grafana
## Default values: https://github.com/grafana-community/helm-charts/blob/main/charts/grafana/values.yaml
##

readinessProbe:
  httpGet:
    scheme: HTTPS
    port: 3001
livenessProbe:
  httpGet:
    scheme: HTTPS
    port: 3001

extraSecretMounts:
- name: v4m-grafana-tls
  mountPath: /cert
  secretName: v4m-grafana-tls-secret
  readOnly: true
  subPath: ""

sidecar:
  dashboards:
    reloadURL: "https://localhost:3001/api/admin/provisioning/dashboards/reload"    
    env:
      REQ_SKIP_TLS_VERIFY: true
  datasources:
    defaultDatasourceEnabled: false
    reloadURL: "https://localhost:3001/api/admin/provisioning/datasources/reload"    
    env:
      REQ_SKIP_TLS_VERIFY: true

service:
  enabled: false

"grafana.ini":
  server:
    protocol: https
    http_port: 3001
    cert_file: /cert/tls.crt
    cert_key: /cert/tls.key
