# Service used for internal TLS when not using OpenShift authentication
apiVersion: v1
kind: Service
metadata:
  name: v4m-grafana
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: v4m-grafana-tls-secret
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: v4m-grafana
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: v4m-grafana
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP
