image:
  tag: "9.0.3"
extraLabels:
  v4m.sas.com/tenant: __TENANT__
readinessProbe: null
livenessProbe: null
rbac:
  pspEnabled: false
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard-__TENANT__
  datasources:
    enabled: true
    label: grafana_datasource-__TENANT__
deploymentStrategy:
  type: Recreate
persistence:
  type: pvc
  enabled: true
  # Provide custom storageClassName here if needed
  # storageClassName: nfs-client
  finalizers:
    - kubernetes.io/pvc-protection
  accessModes:
    - ReadWriteOnce
  size: 5Gi
initChownData:
  enabled: false
# Set to null to disable securityContext for OpenShift
securityContext: null
service:
  enabled: false
serviceAccount:
  # Service account created prior to helm install since the token is needed
  # above in the datasource configuration
  create: false
  name: grafana-serviceaccount-__TENANT__
serviceMonitor:
  enabled: false
testFramework:
  enabled: false
"grafana.ini":
  server:
    http_addr: 127.0.0.1
    http_port: 3000
  dashboards:
    default_home_dashboard_path: /tmp/dashboards/cas-dashboard.json
  analytics:
    check_for_updates: false
  log:
    mode: console
  "log.console":
      format: json
