# Service used for internal TLS when not using OpenShift authentication
apiVersion: v1
kind: Service
metadata:
  name: v4m-grafana-__TENANT__
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: v4m-grafana-__TENANT__-tls-secret
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.3.1
    v4m.sas.com/tenant: __TENANT__
spec:
  ports:
  - name: service
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP
