# NOTE: Refer to https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/stable/ARTIFACT_INVENTORY.md
#       to identify the current Helm chart version in use by this project.  The links below point to
#       the 'main' branch as a general reference and the contents will likely differ to some degree.
#
# Helm Chart: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/Chart.yaml
# Default values: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/values.yaml
#

# image:
#  repository: quay.io/prometheuscommunity/elasticsearch-exporter
#  tag: v1.6.0

# es:
##  The env vars ES_USER and ES_PASSWORD are set, by default,
##  based on the K8s secret internal-user-metricgetter
#   uri: https://$(ES_USER):$(ES_PASSWORD)@v4m-search:9200
