# NOTE: Refer to https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/stable/ARTIFACT_INVENTORY.md
#       to identify the current Helm chart version in use by this project.  The links below point to
#       the 'main' branch as a general reference and the contents will likely differ to some degree.
#
# Chart:  https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit
# Default values: https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml
#

#image:
#  tag: 2.1.10

