kibana:
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    # ingressClassName is not currently supported by the Open Distro helm chart
    # ingressClassName: nginx
    path: /
    hosts:
    - kibana.logging.host.cluster.example.com

# Elasticsearch ingress is optional
# Uncomment this section only if external API access is required
# elasticsearch:
#   client:
#     ingress:
#       annotations:
#         kubernetes.io/ingress.class: nginx
#         nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#       enabled: true
#       # ingressClassName is not currently supported by the Open Distro helm chart
#       # ingressClassName: nginx
#       path: /
#       hosts:
#       - elasticsearch.logging.host.cluster.example.com
