kibana:
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: true
    path: /
    hosts:
    - kibana.logging.host.cluster.example.com

elasticsearch:
  client:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      enabled: true
      path: /
      hosts:
      - elasticsearch.logging.host.cluster.example.com
