## Sample: contour/path-based-ingress Version: 0.0.1


apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-monitoring
spec:
  virtualhost:
    fqdn: host.cluster.example.com
    tls:
      secretName: alertmanager-ingress-tls-secret
  routes:

#
# Grafana
#

    - conditions:
      - prefix: /grafana
      services:
        - name: v4m-grafana
          port: 3000
          protocol: tls

# This sample does NOT make the Prometheus and Alertmanager accessible by default.
# However, you can make one or both of these web applications
# accessible by uncommenting out the approprate section below.
# To do so, remove the double hash marks (##) from each line in the section.


# Note that Prometheus and Alertmanager
# do not have any authentication configured by default, and exposing
# an unauthenticated applicaton without other restrictions in place
# is insecure.

#
# Alertmanager
#

##    - conditions:
##      - prefix: /alertmanager
##      services:
##        - name: v4m-alertmanager
##          port: 9093
##          protocol: tls

#
# Prometheus
#

##    - conditions:
##      - prefix: /prometheus
##      services:
##        - name: v4m-prometheus
##          port: 9090
##          protocol: tls
