# Sample: contour/path-based-ingress Version: 0.2.2

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-grafana
spec:
  routes:
    - conditions:
      - prefix: /grafana
      services:
        - name: v4m-grafana
          port: 3000
          protocol: tls
