apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: es-admin-tls-cert
spec:
  commonName: es-admin
  dnsNames:
  - localhost
  - v4m-es-client-service
  issuerRef:
    kind: Issuer
    name: namespace-issuer
  secretName: es-admin-tls-secret
  privateKey:
    encoding: PKCS8
  subject:
    organizations:
    - cert-manager
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth