## Sample: contour/path-based-ingress Version: 0.2.1

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-search
spec:
  routes:
    - conditions:
      - prefix: /opensearch
      services:
        - name: v4m-search
          port: 9200
          protocol: tls
      pathRewritePolicy:
        replacePrefix:
        - prefix: /opensearch
          replacement: /


