## Sample: contour/path-based-ingress Version: 0.2.2

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-osd
spec:
  routes:
    - conditions:
      - prefix: /dashboards
      services:
        - name: v4m-osd
          port: 5601
          protocol: tls
      pathRewritePolicy:
        replacePrefix:
        - prefix: /dashboards
          replacement: /

