# Chart: https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm
# Default values: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/values.yaml

elasticsearch:
  master:
    persistence:
      storageClass: azuredisk-v4m

  data:
    persistence:
      storageClass: azuredisk-v4m

# The 'kibana:' section below can be replaced by the same section from
# one of the [tls samples](/samples/tls).
kibana:
  extraEnvs:
  # Needed for path-based ingress
  - name: SERVER_BASEPATH
    value: /kibana
  # Username & password need to be set here since helm *replaces* array values
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: username
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
       secretKeyRef:
          name: internal-user-kibanaserver
          key: password

  service:
    type: ClusterIP
    nodePort: null
  
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite (?i)/kibana/(.*) /$1 break;
        rewrite (?i)/kibana$ / break;
      nginx.ingress.kubernetes.io/rewrite-target: /kibana
    enabled: true
    path: /kibana
    hosts:
    - host.mycluster.example.com
