# Turn off in-cluster Alertmanager
alertmanager:
  enabled: false

# Point Prometheus to the 'my-external-alertmanager' service
prometheus:
  prometheusSpec:
    alertingEndpoints:
    - name: my-external-alertmanager
      namespace: monitoring
      port: http
      scheme: http
