apiVersion: v1
kind: Service
metadata:
  name: v4m-mcp-server
  namespace: monitoring
spec:
  # No auth exists on this endpoint yet (Still need to setup)
  type: ClusterIP
  selector:
    app: v4m-mcp-server
  ports:
  - port: 8000
    targetPort: 8000
